// Generated by BeanMaker, on April 1, 2018 2:03:33 AM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.text.DateFormat;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import org.beanmaker.util.BeanInternals;
import org.beanmaker.util.DBQueries;
import org.beanmaker.util.DbBeanInterface;
import org.beanmaker.util.ErrorMessage;
import org.beanmaker.util.FormatCheckHelper;
import org.beanmaker.util.IdNamePair;
import org.beanmaker.util.ToStringMaker;

import org.dbbeans.sql.DBQueryRetrieveData;
import org.dbbeans.sql.DBQuerySetup;
import org.dbbeans.sql.DBQuerySetupProcess;
import org.dbbeans.sql.DBTransaction;

import org.dbbeans.sql.queries.BooleanCheckQuery;

import org.dbbeans.util.Dates;
import org.dbbeans.util.SimpleInputDateFormat;
import org.dbbeans.util.Strings;

public abstract class DailyBase extends DbBean implements DbBeanInterface {
	private long id;
	private long idRegistryEntry;
	private boolean businessDaysOnly;
	private int everyXDays;
	private String everyXDaysStr = "";
	private Date start;
	private String startStr = "";
	private long idEnding;

	protected static final String DATABASE_TABLE_NAME = "schdlr_daily";
	protected static final String DATABASE_FIELD_LIST = "schdlr_daily.id, schdlr_daily.id_registry_entry, schdlr_daily.business_days_only, schdlr_daily.every_x_days, schdlr_daily.start, schdlr_daily.id_ending";

	protected final BeanInternals dailyInternals = new BeanInternals("org-dbbeans-scheduler-Daily");
	protected static final DailyParameters DAILY_PARAMETERS = new DailyParameters();

	public DailyBase() { }

	public DailyBase(final long id) {
		setId(id);
	}

	public DailyBase(final DailyBase dailyModel) {
		id = 0;
		idRegistryEntry = dailyModel.idRegistryEntry;
		businessDaysOnly = dailyModel.businessDaysOnly;
		setEveryXDays(dailyModel.everyXDays);
		setStart(dailyModel.start);
		idEnding = dailyModel.idEnding;
	}

	protected DailyBase(final long id, final long idRegistryEntry, final boolean businessDaysOnly, final int everyXDays, final Date start, final long idEnding) {
		this.id = id;
		this.idRegistryEntry = idRegistryEntry;
		this.businessDaysOnly = businessDaysOnly;
		setEveryXDays(everyXDays);
		setStart(start);
		this.idEnding = idEnding;
	}

	protected DailyBase(final ResultSet rs) throws SQLException {
		this(rs.getLong(1), rs.getLong(2), rs.getBoolean(3), rs.getInt(4), rs.getDate(5), rs.getLong(6));
	}

	@Override
	public void setId(final long id) {
		class DataFromDBQuery implements DBQuerySetupProcess {
			long idRegistryEntry = 0;
			boolean businessDaysOnly = false;
			int everyXDays = 0;
			Date start = null;
			long idEnding = 0;
			boolean idOK = false;

			@Override
			public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
				stat.setLong(1, id);
			}

			@Override
			public void processResultSet(final ResultSet rs) throws SQLException {
				if (rs.next()) {
					idRegistryEntry = rs.getLong(1);
					businessDaysOnly = rs.getBoolean(2);
					everyXDays = rs.getInt(3);
					start = rs.getDate(4);
					idEnding = rs.getLong(5);
					idOK = true;
				}
			}
		}

		if (id <= 0)
			throw new IllegalArgumentException("id = " + id + " <= 0");

		final DataFromDBQuery dataFromDBQuery = new DataFromDBQuery();
		dbAccess.processQuery("SELECT id_registry_entry, business_days_only, every_x_days, start, id_ending FROM schdlr_daily WHERE id=?", dataFromDBQuery);

		if (!dataFromDBQuery.idOK)
			throw new IllegalArgumentException("id = " + id + " does not exist");

		initExtraDbActions(id);

		this.id = id;
		this.idRegistryEntry = dataFromDBQuery.idRegistryEntry;
		this.businessDaysOnly = dataFromDBQuery.businessDaysOnly;
		this.everyXDays = dataFromDBQuery.everyXDays;
		everyXDaysStr = String.valueOf(everyXDays);
		this.start = dataFromDBQuery.start;
		startStr = convertDateToString(start);
		this.idEnding = dataFromDBQuery.idEnding;

		postInitActions();
	}

	protected void initExtraDbActions(final long id) { }

	protected void postInitActions() { }

	@Override
	public void resetId() {
		id = 0;
	}

	public void refreshFromDataBase() {
		if (id == 0)
			throw new IllegalArgumentException("Cannot refresh bean not yet commited to database");

		setId(id);
	}

	@Override
	public boolean equals(final Object object) {
		if (id == 0)
			return false;

		if (object instanceof Daily)
			return ((Daily) object).getId() == id;

		return false;
	}

	@Override
	public int hashCode() {
		if (id == 0)
			return -1;

		return 31 * ((int) (id ^ (id >>> 32))) + 17;
	}

	@Override
	public String toString() {
		final ToStringMaker stringMaker = new ToStringMaker(this);
		stringMaker.addField("idRegistryEntry", idRegistryEntry);
		stringMaker.addField("businessDaysOnly", businessDaysOnly);
		stringMaker.addField("everyXDays", everyXDays);
		stringMaker.addField("everyXDaysStr", everyXDaysStr);
		stringMaker.addField("start", start);
		stringMaker.addField("startStr", startStr);
		stringMaker.addField("idEnding", idEnding);
		return stringMaker.toString();
	}

	public void setIdRegistryEntry(final long idRegistryEntry) {
		this.idRegistryEntry = idRegistryEntry;
	}

	public void setRegistryEntry(final RegistryEntry registryEntry) {
		if (registryEntry.getId() == 0)
			throw new IllegalArgumentException("Cannot accept uninitialized RegistryEntry bean (id = 0) as argument.");

		idRegistryEntry = registryEntry.getId();
	}

	public void setBusinessDaysOnly(final boolean businessDaysOnly) {
		this.businessDaysOnly = businessDaysOnly;
	}

	public void setEveryXDays(final int everyXDays) {
		this.everyXDays = everyXDays;
		everyXDaysStr = Integer.toString(everyXDays);
	}

	public void setEveryXDaysStr(final String everyXDaysStr) {
		this.everyXDaysStr = everyXDaysStr;
	}

	public void setStart(final Date start) {
		if (start == null)
			this.start = null;
		else
			this.start = new Date(start.getTime());
		startStr = convertDateToString(start);
	}

	public void setStartStr(final String startStr) {
		this.startStr = startStr;
	}

	public void setIdEnding(final long idEnding) {
		this.idEnding = idEnding;
	}

	public void setEnding(final Ending ending) {
		if (ending.getId() == 0)
			throw new IllegalArgumentException("Cannot accept uninitialized Ending bean (id = 0) as argument.");

		idEnding = ending.getId();
	}

	@Override
	public long getId() {
		return id;
	}

	public long getIdRegistryEntry() {
		return idRegistryEntry;
	}

	public RegistryEntry getRegistryEntry() {
		return new RegistryEntry(idRegistryEntry);
	}

	public boolean isBusinessDaysOnly() {
		return businessDaysOnly;
	}

	public String getBusinessDaysOnlyVal() {
		if (businessDaysOnly)
			return dailyInternals.getLabel("true_value");

		return dailyInternals.getLabel("false_value");
	}

	public int getEveryXDays() {
		return everyXDays;
	}

	public String getEveryXDaysStr() {
		return everyXDaysStr;
	}

	public Date getStart() {
		if (start == null)
			return null;

		return new Date(start.getTime());
	}

	public String getStartStr() {
		return startStr;
	}

	public String getStartFormatted() {
		if (isStartEmpty()) {
			if (isStartRequired())
				throw new IllegalArgumentException("Cannot display bad data");
			return "";
		}

		if (!isStartOK())
			throw new IllegalArgumentException("Cannot display bad data");

		return formatDate(convertStringToDate(startStr));
	}

	public long getIdEnding() {
		return idEnding;
	}

	public Ending getEnding() {
		return new Ending(idEnding);
	}

	public String getIdRegistryEntryLabel() {
		return dailyInternals.getLabel("idRegistryEntry");
	}

	public String getBusinessDaysOnlyLabel() {
		return dailyInternals.getLabel("businessDaysOnly");
	}

	public String getEveryXDaysLabel() {
		return dailyInternals.getLabel("everyXDays");
	}

	public String getStartLabel() {
		return dailyInternals.getLabel("start");
	}

	public String getIdEndingLabel() {
		return dailyInternals.getLabel("idEnding");
	}

	public boolean isIdRequired() {
		return true;
	}

	public boolean isIdRegistryEntryRequired() {
		return true;
	}

	public boolean isBusinessDaysOnlyRequired() {
		return true;
	}

	public boolean isEveryXDaysRequired() {
		return true;
	}

	public boolean isStartRequired() {
		return true;
	}

	public boolean isIdEndingRequired() {
		return false;
	}

	public boolean isIdToBeUnique() {
		return true;
	}

	public boolean isIdRegistryEntryToBeUnique() {
		return true;
	}

	public boolean isBusinessDaysOnlyToBeUnique() {
		return false;
	}

	public boolean isEveryXDaysToBeUnique() {
		return false;
	}

	public boolean isStartToBeUnique() {
		return false;
	}

	public boolean isIdEndingToBeUnique() {
		return true;
	}

	@Override
	public void updateDB() {
		preUpdateConversions();

		if (id == 0) {
			createRecord();
			return;
		}

		if (id > 0) {
			updateRecord();
			return;
		}

		assert (false) : "id < 0 ?!?";
	}

	public long updateDB(final DBTransaction transaction) {
		if (DAILY_PARAMETERS.USE_CACHE)
			throw new UnsupportedOperationException("Cannot cache intermediate updates.");

		preUpdateConversions(transaction);

		if (id == 0) {
			id = createRecord(transaction);
			return id;
		}

		if (id > 0) {
			updateRecord(transaction);
			return id;
		}

		assert (false) : "id < 0 ?!?";
		return -1;
	}

	@Override
	public void preUpdateConversions() {
		preUpdateConversions(null);
	}

	protected void preUpdateConversions(final DBTransaction transaction) {
		if (!isDataOK(transaction))
			throw new IllegalArgumentException(ErrorMessage.toStrings(getErrorMessages()));

		everyXDays = Strings.getIntVal(everyXDaysStr);
		if (!Strings.isEmpty(startStr))
			start = convertStringToDate(startStr);
		else
			start = null;
	}

	@Override
	public boolean isDataOK() {
		return isDataOK(null);
	}

	protected boolean isDataOK(final DBTransaction transaction) {
		dailyInternals.clearErrorMessages();
		boolean ok = true;

		ok = checkDataForIdRegistryEntry(transaction) && ok;
		ok = checkDataForEveryXDays() && ok;
		ok = checkDataForStart() && ok;
		ok = checkDataForIdEnding(transaction) && ok;

		return ok;
	}

	protected boolean checkDataForIdRegistryEntry() {
		return checkDataForIdRegistryEntry(null);
	}

	protected boolean checkDataForIdRegistryEntry(final DBTransaction transaction) {
		if (isIdRegistryEntryEmpty()) {
			if (isIdRegistryEntryRequired()) {
				dailyInternals.addErrorMessage(id, "idRegistryEntry", getIdRegistryEntryLabel(), getIdRegistryEntryEmptyErrorMessage());
				return false;
			}
		} else if (!isIdRegistryEntryOK(transaction)) {
			dailyInternals.addErrorMessage(id, "idRegistryEntry", getIdRegistryEntryLabel(), getIdRegistryEntryBadFormatErrorMessage());
			return false;
		} else if (isIdRegistryEntryToBeUnique() && !isIdRegistryEntryUnique()) {
			dailyInternals.addErrorMessage(id, "idRegistryEntry", getIdRegistryEntryLabel(), getIdRegistryEntryNotUniqueErrorMessage());
			return false;
		}

		return true;
	}

	protected boolean checkDataForEveryXDays() {
		if (isEveryXDaysEmpty()) {
			if (isEveryXDaysRequired()) {
				dailyInternals.addErrorMessage(id, "everyXDays", getEveryXDaysLabel(), getEveryXDaysEmptyErrorMessage());
				return false;
			}
		} else if (!isEveryXDaysOK()) {
			dailyInternals.addErrorMessage(id, "everyXDays", getEveryXDaysLabel(), getEveryXDaysBadFormatErrorMessage());
			return false;
		} else if (isEveryXDaysToBeUnique() && !isEveryXDaysUnique()) {
			dailyInternals.addErrorMessage(id, "everyXDays", getEveryXDaysLabel(), getEveryXDaysNotUniqueErrorMessage());
			return false;
		}

		return true;
	}

	protected boolean checkDataForStart() {
		if (isStartEmpty()) {
			if (isStartRequired()) {
				dailyInternals.addErrorMessage(id, "start", getStartLabel(), getStartEmptyErrorMessage());
				return false;
			}
		} else if (!isStartOK()) {
			dailyInternals.addErrorMessage(id, "start", getStartLabel(), getStartBadFormatErrorMessage());
			return false;
		} else if (isStartToBeUnique() && !isStartUnique()) {
			dailyInternals.addErrorMessage(id, "start", getStartLabel(), getStartNotUniqueErrorMessage());
			return false;
		}

		return true;
	}

	protected boolean checkDataForIdEnding() {
		return checkDataForIdEnding(null);
	}

	protected boolean checkDataForIdEnding(final DBTransaction transaction) {
		if (isIdEndingEmpty()) {
			if (isIdEndingRequired()) {
				dailyInternals.addErrorMessage(id, "idEnding", getIdEndingLabel(), getIdEndingEmptyErrorMessage());
				return false;
			}
		} else if (!isIdEndingOK(transaction)) {
			dailyInternals.addErrorMessage(id, "idEnding", getIdEndingLabel(), getIdEndingBadFormatErrorMessage());
			return false;
		} else if (isIdEndingToBeUnique() && !isIdEndingUnique()) {
			dailyInternals.addErrorMessage(id, "idEnding", getIdEndingLabel(), getIdEndingNotUniqueErrorMessage());
			return false;
		}

		return true;
	}

	public boolean isIdRegistryEntryEmpty() {
		return idRegistryEntry == 0;
	}

	public boolean isEveryXDaysEmpty() {
		return Strings.isEmpty(everyXDaysStr);
	}

	public boolean isStartEmpty() {
		return Strings.isEmpty(startStr);
	}

	public boolean isIdEndingEmpty() {
		return idEnding == 0;
	}

	public String getIdRegistryEntryEmptyErrorMessage() {
		return dailyInternals.getRequiredErrorMessage("idRegistryEntry");
	}

	public String getEveryXDaysEmptyErrorMessage() {
		return dailyInternals.getRequiredErrorMessage("everyXDays");
	}

	public String getStartEmptyErrorMessage() {
		return dailyInternals.getRequiredErrorMessage("start");
	}

	public String getIdEndingEmptyErrorMessage() {
		return dailyInternals.getRequiredErrorMessage("idEnding");
	}

	public boolean isIdRegistryEntryOK() {
		return isIdRegistryEntryOK(null);
	}

	protected boolean isIdRegistryEntryOK(final DBTransaction transaction) {
		if (transaction == null)
			return RegistryEntry.isIdOK(idRegistryEntry);

		return RegistryEntry.isIdOK(idRegistryEntry, transaction);
	}

	public boolean isEveryXDaysOK() {
		return FormatCheckHelper.isIntNumber(everyXDaysStr);
	}

	public boolean isStartOK() {
		return validateDateFormat(startStr);
	}

	public boolean isIdEndingOK() {
		return isIdEndingOK(null);
	}

	protected boolean isIdEndingOK(final DBTransaction transaction) {
		if (transaction == null)
			return Ending.isIdOK(idEnding);

		return Ending.isIdOK(idEnding, transaction);
	}

	public String getIdRegistryEntryBadFormatErrorMessage() {
		return dailyInternals.getBadFormatErrorMessage("idRegistryEntry");
	}

	public String getEveryXDaysBadFormatErrorMessage() {
		return dailyInternals.getBadFormatErrorMessage("everyXDays");
	}

	public String getStartBadFormatErrorMessage() {
		return dailyInternals.getBadFormatErrorMessage("start");
	}

	public String getIdEndingBadFormatErrorMessage() {
		return dailyInternals.getBadFormatErrorMessage("idEnding");
	}

	public boolean isIdRegistryEntryUnique() {
		return !dbAccess.processQuery("SELECT id FROM schdlr_daily WHERE id_registry_entry=? AND id <> ?", new BooleanCheckQuery() {
			@Override
			public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
				stat.setLong(1, idRegistryEntry);
				stat.setLong(2, id);
			}
		});
	}

	public boolean isEveryXDaysUnique() {
		return !dbAccess.processQuery("SELECT id FROM schdlr_daily WHERE every_x_days=? AND id <> ?", new BooleanCheckQuery() {
			@Override
			public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
				stat.setInt(1, everyXDays);
				stat.setLong(2, id);
			}
		});
	}

	public boolean isStartUnique() {
		return !dbAccess.processQuery("SELECT id FROM schdlr_daily WHERE start=? AND id <> ?", new BooleanCheckQuery() {
			@Override
			public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
				stat.setDate(1, start);
				stat.setLong(2, id);
			}
		});
	}

	public boolean isIdEndingUnique() {
		return !dbAccess.processQuery("SELECT id FROM schdlr_daily WHERE id_ending=? AND id <> ?", new BooleanCheckQuery() {
			@Override
			public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
				stat.setLong(1, idEnding);
				stat.setLong(2, id);
			}
		});
	}

	public String getIdRegistryEntryNotUniqueErrorMessage() {
		return dailyInternals.getNotUniqueErrorMessage("idRegistryEntry");
	}

	public String getEveryXDaysNotUniqueErrorMessage() {
		return dailyInternals.getNotUniqueErrorMessage("everyXDays");
	}

	public String getStartNotUniqueErrorMessage() {
		return dailyInternals.getNotUniqueErrorMessage("start");
	}

	public String getIdEndingNotUniqueErrorMessage() {
		return dailyInternals.getNotUniqueErrorMessage("idEnding");
	}

	@Override
	public List<ErrorMessage> getErrorMessages() {
		return dailyInternals.getErrorMessages();
	}

	@Override
	public void reset() {
		idRegistryEntry = 0;
		businessDaysOnly = false;
		everyXDays = 0;
		everyXDaysStr = "";
		start = null;
		startStr = "";
		idEnding = 0;
		dailyInternals.clearErrorMessages();
	}

	@Override
	public void fullReset() {
		reset();
		id = 0;
	}

	@Override
	public void delete() {
		final DBTransaction transaction = createDBTransaction();
		delete(transaction);
		transaction.commit();

		postDeleteActions();

		if (DAILY_PARAMETERS.USE_CACHE)
			DAILY_PARAMETERS.CACHE_SET.delete(id);

		fullReset();
	}

	public void delete(final DBTransaction transaction) {
		preDeleteExtraDbActions(transaction);
		transaction.addUpdate("DELETE FROM schdlr_daily WHERE id=?", new DBQuerySetup() {
				@Override
				public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
					stat.setLong(1, id);
				}
			});
		deleteExtraDbActions(transaction);
	}

	protected void preDeleteExtraDbActions(final DBTransaction transaction) { }

	protected void deleteExtraDbActions(final DBTransaction transaction) { }

	protected void postDeleteActions() { }

	private class RecordCreationSetup implements DBQuerySetup {
		@Override
		public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
			stat.setLong(1, idRegistryEntry);
			stat.setBoolean(2, businessDaysOnly);
			stat.setInt(3, everyXDays);
			stat.setDate(4, start);
			if (idEnding == 0)
				stat.setNull(5, java.sql.Types.INTEGER);
			else
				stat.setLong(5, idEnding);
		}
	}

	private class RecordUpdateSetup extends RecordCreationSetup {
		@Override
		public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
			super.setupPreparedStatement(stat);
			stat.setLong(6, id);
		}
	}

	private void createRecord() {
		final DBTransaction transaction = createDBTransaction();
		id = createRecord(transaction);
		transaction.commit();
		postCreateActions();
		updateCaching();
	}

	private long createRecord(final DBTransaction transaction) {
		preCreateExtraDbActions(transaction);
		final long id = transaction.addRecordCreation("INSERT INTO schdlr_daily (id_registry_entry, business_days_only, every_x_days, start, id_ending) VALUES (?, ?, ?, ?, ?)", new RecordCreationSetup());
		createExtraDbActions(transaction, id);
		return id;
	}

	protected void preCreateExtraDbActions(final DBTransaction transaction) { }

	protected void createExtraDbActions(final DBTransaction transaction, final long id) { }

	protected void postCreateActions() { }

	private void updateRecord() {
		final DBTransaction transaction = createDBTransaction();
		updateRecord(transaction);
		transaction.commit();
		postUpdateActions();
		updateCaching();
	}

	private void updateRecord(final DBTransaction transaction) {
		preUpdateExtraDbActions(transaction);
		transaction.addUpdate("UPDATE schdlr_daily SET id_registry_entry=?, business_days_only=?, every_x_days=?, start=?, id_ending=? WHERE id=?", new RecordUpdateSetup());
		updateExtraDbActions(transaction);
	}

	protected void preUpdateExtraDbActions(final DBTransaction transaction) { }

	protected void updateExtraDbActions(final DBTransaction transaction) { }

	protected void postUpdateActions() { }

	private void updateCaching() {
		if (DAILY_PARAMETERS.USE_CACHE)
			DAILY_PARAMETERS.CACHE_SET.submit((Daily) this);
	}

	protected String formatDate(final Date date) {
		return DateFormat.getDateInstance(DateFormat.LONG, dailyInternals.getLocale()).format(date);
	}

	protected Date convertStringToDate(final String str) {
		return Dates.getDateFromYYMD(str, "-");
	}

	protected String convertDateToString(final Date date) {
		if (date == null)
			return "";

		return date.toString();
	}

	protected boolean validateDateFormat(final String str) {
		final SimpleInputDateFormat simpleInputDateFormat = new SimpleInputDateFormat(SimpleInputDateFormat.ElementOrder.YYMD, "-");
		return simpleInputDateFormat.validate(str);
	}

	public static List<Daily> getAll() {
		return getAll(DAILY_PARAMETERS.getOrderByFields());
	}

	protected static List<Daily> getAll(final String orderBy) {
		return getSelection(null, orderBy, null);
	}

	private static class GetSelectionQueryProcess implements DBQueryRetrieveData<List<Daily>> {
		@Override
		public List<Daily> processResultSet(final ResultSet rs) throws SQLException {
			final List<Daily> list = new ArrayList<Daily>();

			while (rs.next())
				list.add(new Daily(rs.getLong(1), rs.getLong(2), rs.getBoolean(3), rs.getInt(4), rs.getDate(5), rs.getLong(6)));


			return list;
		}
	}

	protected static List<Daily> getSelection(final String whereClause) {
		return getSelection(whereClause, null);
	}

	protected static List<Daily> getSelection(final String whereClause, final DBQuerySetup setup) {
		return getSelection(whereClause, DAILY_PARAMETERS.getOrderByFields(), setup);
	}

	protected static List<Daily> getSelection(final String whereClause, final String orderBy, final DBQuerySetup setup) {
		if (whereClause == null && setup != null)
			throw new IllegalArgumentException("Cannot accept setup code without a WHERE clause.");

		final StringBuilder query = new StringBuilder();
		query.append("SELECT id, id_registry_entry, business_days_only, every_x_days, start, id_ending FROM schdlr_daily");
		if (whereClause != null)
			query.append(" WHERE ").append(whereClause);
		if (orderBy != null)
			query.append(" ORDER BY ").append(orderBy);

		if (whereClause == null || setup == null)
			return dbAccess.processQuery(query.toString(), new GetSelectionQueryProcess());

		return dbAccess.processQuery(query.toString(), setup, new GetSelectionQueryProcess());
	}

	private static class GetSelectionCountQueryProcess implements DBQueryRetrieveData<Long> {
		@Override
		public Long processResultSet(final ResultSet rs) throws SQLException {
			rs.next();
			return rs.getLong(1);
		}
	}

	protected static long getSelectionCount(final String whereClause) {
		return getSelectionCount(whereClause, null);
	}

	protected static long getSelectionCount(final String whereClause, final DBQuerySetup setup) {
		final String query = "SELECT COUNT(id) FROM schdlr_daily WHERE " + whereClause;

		if (setup == null)
			return dbAccess.processQuery(query, new GetSelectionCountQueryProcess());

		return dbAccess.processQuery(query, setup, new GetSelectionCountQueryProcess());
	}

	public static List<IdNamePair> getIdNamePairs(final List<String> dataFields, final List<String> orderingFields) {
		return getIdNamePairs(null, dataFields, orderingFields);
	}

	protected static List<IdNamePair> getIdNamePairs(final String whereClause, final List<String> dataFields, final List<String> orderingFields) {
		return DBQueries.getIdNamePairs(db, "schdlr_daily", whereClause, dataFields, orderingFields);
	}

	public static long getCount() {
		return DBQueries.getLongCount(db, "schdlr_daily");
	}

	public static boolean isIdOK(final long id) {
		return DBQueries.isIdOK(db, "schdlr_daily", id);
	}

	public static boolean isIdOK(final long id, final DBTransaction transaction) {
		return DBQueries.isIdOK(transaction, "schdlr_daily", id);
	}

	public static String getHumanReadableTitle(final long id) {
		if (id == 0)
			return "";

		return DBQueries.getHumanReadableTitle(db, "schdlr_daily", id, DAILY_PARAMETERS.getNamingFields());
	}

	public static List<Daily> getList(final ResultSet rs) throws SQLException {
		final List<Daily> list = new ArrayList<Daily>();

		while (rs.next())
			list.add(new Daily(rs));


		return list;
	}

	@Override
	public void setLocale(final Locale locale) {
		dailyInternals.setLocale(locale);
	}

}

