// Generated by BeanMaker, on March 31, 2018 4:07:41 AM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import org.beanmaker.util.DbBeanCacheSet;

public class DailyParameters extends DailyParametersBase {
	public static final DbBeanCacheSet<Daily> CACHE_SET = null;
	public static final boolean USE_CACHE = CACHE_SET != null;
}

