// Generated by BeanMaker, on March 31, 2018 4:07:41 AM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import org.dbbeans.sql.DBTransaction;

import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;

public class Daily extends DailyBase {
	public Daily() { }

	public Daily(final long id) {
		super(id);
	}

	public Daily(final Daily dailyModel) {
		super(dailyModel);
	}

	protected Daily(final long id, final long idRegistryEntry, final boolean businessDaysOnly, final int everyXDays, final Date start, final long idEnding) {
		super(id, idRegistryEntry, businessDaysOnly, everyXDays, start, idEnding);
	}

	protected Daily(final ResultSet rs) throws SQLException {
		super(rs);
	}

	public boolean hasEnding() {
		return !isIdEndingEmpty();
	}

	@Override
	protected void preDeleteExtraDbActions(DBTransaction transaction) {
		if (hasEnding())
			getEnding().delete(transaction);
	}
}

