// Generated by BeanMaker, on March 31, 2018 2:21:12 AM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import org.dbbeans.sql.DB;
import org.dbbeans.sql.DBAccess;
import org.dbbeans.sql.DBFromDataSource;
import org.dbbeans.sql.DBTransaction;

public abstract class DbBean {
	protected static final DB db;
	protected static final DBAccess dbAccess;

	private static final String DATA_SOURCE = "java:comp/env/jdbc/dbbean_scheduler";

	static {
		db = new DBFromDataSource(DATA_SOURCE);
		dbAccess = new DBAccess(db);
	}

	public static DBTransaction createDBTransaction() {
		return new DBTransaction(db);
	}
}

