// Generated by BeanMaker, on March 31, 2018 3:52:25 AM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;

public class Ending extends EndingBase {
	public Ending() { }

	public Ending(final long id) {
		super(id);
	}

	public Ending(final Ending endingModel) {
		super(endingModel);
	}

	protected Ending(final long id, final Date endsOn, final int endsAfterXTimes) {
		super(id, endsOn, endsAfterXTimes);
	}

	protected Ending(final ResultSet rs) throws SQLException {
		super(rs);
	}

}

