// Generated by BeanMaker, on March 31, 2018 3:52:25 AM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import org.beanmaker.util.DbBeanCacheSet;

public class EndingParameters extends EndingParametersBase {
	public static final DbBeanCacheSet<Ending> CACHE_SET = null;
	public static final boolean USE_CACHE = CACHE_SET != null;
}

