// Generated by BeanMaker, on April 1, 2018 5:19:43 PM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import org.beanmaker.util.DbBeanCacheSet;

public class MonthParameters extends MonthParametersBase {
	public static final DbBeanCacheSet<Month> CACHE_SET = null;
	public static final boolean USE_CACHE = CACHE_SET != null;
}

