// Generated by BeanMaker, on April 1, 2018 2:28:35 AM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import org.beanmaker.util.DbBeanCacheSet;

public class MonthlyOnDayParameters extends MonthlyOnDayParametersBase {
	public static final DbBeanCacheSet<MonthlyOnDay> CACHE_SET = null;
	public static final boolean USE_CACHE = CACHE_SET != null;
}

