// Generated by BeanMaker, on April 1, 2018 5:19:43 PM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import java.sql.ResultSet;
import java.sql.SQLException;

public class Month extends MonthBase {
	public Month() { }

	public Month(final long id) {
		super(id);
	}

	public Month(final Month monthModel) {
		super(monthModel);
	}

	protected Month(final long id, final String code) {
		super(id, code);
	}

	protected Month(final ResultSet rs) throws SQLException {
		super(rs);
	}

}

