// Generated by BeanMaker, on April 1, 2018 4:06:01 AM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import org.dbbeans.sql.DBTransaction;

import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;

public class MonthlyOnWeekday extends MonthlyOnWeekdayBase {
	public MonthlyOnWeekday() { }

	public MonthlyOnWeekday(final long id) {
		super(id);
	}

	public MonthlyOnWeekday(final MonthlyOnWeekday monthlyOnWeekdayModel) {
		super(monthlyOnWeekdayModel);
	}

	protected MonthlyOnWeekday(final long id, final long idRegistryEntry, final long idWeekdayPlaceInMonth, final long idWeekday, final int everyXMonth, final Date start, final long idEnding) {
		super(id, idRegistryEntry, idWeekdayPlaceInMonth, idWeekday, everyXMonth, start, idEnding);
	}

	protected MonthlyOnWeekday(final ResultSet rs) throws SQLException {
		super(rs);
	}

	public boolean hasEnding() {
		return !isIdEndingEmpty();
	}

	@Override
	protected void preDeleteExtraDbActions(DBTransaction transaction) {
		if (hasEnding())
			getEnding().delete(transaction);
	}

}

