// Generated by BeanMaker, on April 1, 2018 4:06:01 AM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.text.DateFormat;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import org.beanmaker.util.BeanInternals;
import org.beanmaker.util.DBQueries;
import org.beanmaker.util.DbBeanInterface;
import org.beanmaker.util.ErrorMessage;
import org.beanmaker.util.FormatCheckHelper;
import org.beanmaker.util.IdNamePair;
import org.beanmaker.util.ToStringMaker;

import org.dbbeans.sql.DBQueryRetrieveData;
import org.dbbeans.sql.DBQuerySetup;
import org.dbbeans.sql.DBQuerySetupProcess;
import org.dbbeans.sql.DBTransaction;

import org.dbbeans.sql.queries.BooleanCheckQuery;

import org.dbbeans.util.Dates;
import org.dbbeans.util.SimpleInputDateFormat;
import org.dbbeans.util.Strings;

public abstract class MonthlyOnWeekdayBase extends DbBean implements DbBeanInterface {
	private long id;
	private long idRegistryEntry;
	private long idWeekdayPlaceInMonth;
	private long idWeekday;
	private int everyXMonth;
	private String everyXMonthStr = "";
	private Date start;
	private String startStr = "";
	private long idEnding;

	protected static final String DATABASE_TABLE_NAME = "schdlr_monthly_on_weekday";
	protected static final String DATABASE_FIELD_LIST = "schdlr_monthly_on_weekday.id, schdlr_monthly_on_weekday.id_registry_entry, schdlr_monthly_on_weekday.id_weekday_place_in_month, schdlr_monthly_on_weekday.id_weekday, schdlr_monthly_on_weekday.every_x_month, schdlr_monthly_on_weekday.start, schdlr_monthly_on_weekday.id_ending";

	protected final BeanInternals monthlyOnWeekdayInternals = new BeanInternals("org-dbbeans-scheduler-MonthlyOnWeekday");
	protected static final MonthlyOnWeekdayParameters MONTHLY_ON_WEEKDAY_PARAMETERS = new MonthlyOnWeekdayParameters();

	public MonthlyOnWeekdayBase() { }

	public MonthlyOnWeekdayBase(final long id) {
		setId(id);
	}

	public MonthlyOnWeekdayBase(final MonthlyOnWeekdayBase monthlyOnWeekdayModel) {
		id = 0;
		idRegistryEntry = monthlyOnWeekdayModel.idRegistryEntry;
		idWeekdayPlaceInMonth = monthlyOnWeekdayModel.idWeekdayPlaceInMonth;
		idWeekday = monthlyOnWeekdayModel.idWeekday;
		setEveryXMonth(monthlyOnWeekdayModel.everyXMonth);
		setStart(monthlyOnWeekdayModel.start);
		idEnding = monthlyOnWeekdayModel.idEnding;
	}

	protected MonthlyOnWeekdayBase(final long id, final long idRegistryEntry, final long idWeekdayPlaceInMonth, final long idWeekday, final int everyXMonth, final Date start, final long idEnding) {
		this.id = id;
		this.idRegistryEntry = idRegistryEntry;
		this.idWeekdayPlaceInMonth = idWeekdayPlaceInMonth;
		this.idWeekday = idWeekday;
		setEveryXMonth(everyXMonth);
		setStart(start);
		this.idEnding = idEnding;
	}

	protected MonthlyOnWeekdayBase(final ResultSet rs) throws SQLException {
		this(rs.getLong(1), rs.getLong(2), rs.getLong(3), rs.getLong(4), rs.getInt(5), rs.getDate(6), rs.getLong(7));
	}

	@Override
	public void setId(final long id) {
		class DataFromDBQuery implements DBQuerySetupProcess {
			long idRegistryEntry = 0;
			long idWeekdayPlaceInMonth = 0;
			long idWeekday = 0;
			int everyXMonth = 0;
			Date start = null;
			long idEnding = 0;
			boolean idOK = false;

			@Override
			public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
				stat.setLong(1, id);
			}

			@Override
			public void processResultSet(final ResultSet rs) throws SQLException {
				if (rs.next()) {
					idRegistryEntry = rs.getLong(1);
					idWeekdayPlaceInMonth = rs.getLong(2);
					idWeekday = rs.getLong(3);
					everyXMonth = rs.getInt(4);
					start = rs.getDate(5);
					idEnding = rs.getLong(6);
					idOK = true;
				}
			}
		}

		if (id <= 0)
			throw new IllegalArgumentException("id = " + id + " <= 0");

		final DataFromDBQuery dataFromDBQuery = new DataFromDBQuery();
		dbAccess.processQuery("SELECT id_registry_entry, id_weekday_place_in_month, id_weekday, every_x_month, start, id_ending FROM schdlr_monthly_on_weekday WHERE id=?", dataFromDBQuery);

		if (!dataFromDBQuery.idOK)
			throw new IllegalArgumentException("id = " + id + " does not exist");

		initExtraDbActions(id);

		this.id = id;
		this.idRegistryEntry = dataFromDBQuery.idRegistryEntry;
		this.idWeekdayPlaceInMonth = dataFromDBQuery.idWeekdayPlaceInMonth;
		this.idWeekday = dataFromDBQuery.idWeekday;
		this.everyXMonth = dataFromDBQuery.everyXMonth;
		everyXMonthStr = String.valueOf(everyXMonth);
		this.start = dataFromDBQuery.start;
		startStr = convertDateToString(start);
		this.idEnding = dataFromDBQuery.idEnding;

		postInitActions();
	}

	protected void initExtraDbActions(final long id) { }

	protected void postInitActions() { }

	@Override
	public void resetId() {
		id = 0;
	}

	public void refreshFromDataBase() {
		if (id == 0)
			throw new IllegalArgumentException("Cannot refresh bean not yet commited to database");

		setId(id);
	}

	@Override
	public boolean equals(final Object object) {
		if (id == 0)
			return false;

		if (object instanceof MonthlyOnWeekday)
			return ((MonthlyOnWeekday) object).getId() == id;

		return false;
	}

	@Override
	public int hashCode() {
		if (id == 0)
			return -1;

		return 31 * ((int) (id ^ (id >>> 32))) + 17;
	}

	@Override
	public String toString() {
		final ToStringMaker stringMaker = new ToStringMaker(this);
		stringMaker.addField("idRegistryEntry", idRegistryEntry);
		stringMaker.addField("idWeekdayPlaceInMonth", idWeekdayPlaceInMonth);
		stringMaker.addField("idWeekday", idWeekday);
		stringMaker.addField("everyXMonth", everyXMonth);
		stringMaker.addField("everyXMonthStr", everyXMonthStr);
		stringMaker.addField("start", start);
		stringMaker.addField("startStr", startStr);
		stringMaker.addField("idEnding", idEnding);
		return stringMaker.toString();
	}

	public void setIdRegistryEntry(final long idRegistryEntry) {
		this.idRegistryEntry = idRegistryEntry;
	}

	public void setRegistryEntry(final RegistryEntry registryEntry) {
		if (registryEntry.getId() == 0)
			throw new IllegalArgumentException("Cannot accept uninitialized RegistryEntry bean (id = 0) as argument.");

		idRegistryEntry = registryEntry.getId();
	}

	public void setIdWeekdayPlaceInMonth(final long idWeekdayPlaceInMonth) {
		this.idWeekdayPlaceInMonth = idWeekdayPlaceInMonth;
	}

	public void setWeekdayPlaceInMonth(final WeekdayPlaceInMonth weekdayPlaceInMonth) {
		if (weekdayPlaceInMonth.getId() == 0)
			throw new IllegalArgumentException("Cannot accept uninitialized WeekdayPlaceInMonth bean (id = 0) as argument.");

		idWeekdayPlaceInMonth = weekdayPlaceInMonth.getId();
	}

	public void setIdWeekday(final long idWeekday) {
		this.idWeekday = idWeekday;
	}

	public void setWeekday(final Weekday weekday) {
		if (weekday.getId() == 0)
			throw new IllegalArgumentException("Cannot accept uninitialized Weekday bean (id = 0) as argument.");

		idWeekday = weekday.getId();
	}

	public void setEveryXMonth(final int everyXMonth) {
		this.everyXMonth = everyXMonth;
		everyXMonthStr = Integer.toString(everyXMonth);
	}

	public void setEveryXMonthStr(final String everyXMonthStr) {
		this.everyXMonthStr = everyXMonthStr;
	}

	public void setStart(final Date start) {
		if (start == null)
			this.start = null;
		else
			this.start = new Date(start.getTime());
		startStr = convertDateToString(start);
	}

	public void setStartStr(final String startStr) {
		this.startStr = startStr;
	}

	public void setIdEnding(final long idEnding) {
		this.idEnding = idEnding;
	}

	public void setEnding(final Ending ending) {
		if (ending.getId() == 0)
			throw new IllegalArgumentException("Cannot accept uninitialized Ending bean (id = 0) as argument.");

		idEnding = ending.getId();
	}

	@Override
	public long getId() {
		return id;
	}

	public long getIdRegistryEntry() {
		return idRegistryEntry;
	}

	public RegistryEntry getRegistryEntry() {
		return new RegistryEntry(idRegistryEntry);
	}

	public long getIdWeekdayPlaceInMonth() {
		return idWeekdayPlaceInMonth;
	}

	public WeekdayPlaceInMonth getWeekdayPlaceInMonth() {
		return new WeekdayPlaceInMonth(idWeekdayPlaceInMonth);
	}

	public long getIdWeekday() {
		return idWeekday;
	}

	public Weekday getWeekday() {
		return new Weekday(idWeekday);
	}

	public int getEveryXMonth() {
		return everyXMonth;
	}

	public String getEveryXMonthStr() {
		return everyXMonthStr;
	}

	public Date getStart() {
		if (start == null)
			return null;

		return new Date(start.getTime());
	}

	public String getStartStr() {
		return startStr;
	}

	public String getStartFormatted() {
		if (isStartEmpty()) {
			if (isStartRequired())
				throw new IllegalArgumentException("Cannot display bad data");
			return "";
		}

		if (!isStartOK())
			throw new IllegalArgumentException("Cannot display bad data");

		return formatDate(convertStringToDate(startStr));
	}

	public long getIdEnding() {
		return idEnding;
	}

	public Ending getEnding() {
		return new Ending(idEnding);
	}

	public String getIdRegistryEntryLabel() {
		return monthlyOnWeekdayInternals.getLabel("idRegistryEntry");
	}

	public String getIdWeekdayPlaceInMonthLabel() {
		return monthlyOnWeekdayInternals.getLabel("idWeekdayPlaceInMonth");
	}

	public String getIdWeekdayLabel() {
		return monthlyOnWeekdayInternals.getLabel("idWeekday");
	}

	public String getEveryXMonthLabel() {
		return monthlyOnWeekdayInternals.getLabel("everyXMonth");
	}

	public String getStartLabel() {
		return monthlyOnWeekdayInternals.getLabel("start");
	}

	public String getIdEndingLabel() {
		return monthlyOnWeekdayInternals.getLabel("idEnding");
	}

	public boolean isIdRequired() {
		return true;
	}

	public boolean isIdRegistryEntryRequired() {
		return true;
	}

	public boolean isIdWeekdayPlaceInMonthRequired() {
		return true;
	}

	public boolean isIdWeekdayRequired() {
		return true;
	}

	public boolean isEveryXMonthRequired() {
		return true;
	}

	public boolean isStartRequired() {
		return true;
	}

	public boolean isIdEndingRequired() {
		return false;
	}

	public boolean isIdToBeUnique() {
		return true;
	}

	public boolean isIdRegistryEntryToBeUnique() {
		return true;
	}

	public boolean isIdWeekdayPlaceInMonthToBeUnique() {
		return false;
	}

	public boolean isIdWeekdayToBeUnique() {
		return false;
	}

	public boolean isEveryXMonthToBeUnique() {
		return false;
	}

	public boolean isStartToBeUnique() {
		return false;
	}

	public boolean isIdEndingToBeUnique() {
		return true;
	}

	@Override
	public void updateDB() {
		preUpdateConversions();

		if (id == 0) {
			createRecord();
			return;
		}

		if (id > 0) {
			updateRecord();
			return;
		}

		assert (false) : "id < 0 ?!?";
	}

	public long updateDB(final DBTransaction transaction) {
		if (MONTHLY_ON_WEEKDAY_PARAMETERS.USE_CACHE)
			throw new UnsupportedOperationException("Cannot cache intermediate updates.");

		preUpdateConversions(transaction);

		if (id == 0) {
			id = createRecord(transaction);
			return id;
		}

		if (id > 0) {
			updateRecord(transaction);
			return id;
		}

		assert (false) : "id < 0 ?!?";
		return -1;
	}

	@Override
	public void preUpdateConversions() {
		preUpdateConversions(null);
	}

	protected void preUpdateConversions(final DBTransaction transaction) {
		if (!isDataOK(transaction))
			throw new IllegalArgumentException(ErrorMessage.toStrings(getErrorMessages()));

		everyXMonth = Strings.getIntVal(everyXMonthStr);
		if (!Strings.isEmpty(startStr))
			start = convertStringToDate(startStr);
		else
			start = null;
	}

	@Override
	public boolean isDataOK() {
		return isDataOK(null);
	}

	protected boolean isDataOK(final DBTransaction transaction) {
		monthlyOnWeekdayInternals.clearErrorMessages();
		boolean ok = true;

		ok = checkDataForIdRegistryEntry(transaction) && ok;
		ok = checkDataForIdWeekdayPlaceInMonth(transaction) && ok;
		ok = checkDataForIdWeekday(transaction) && ok;
		ok = checkDataForEveryXMonth() && ok;
		ok = checkDataForStart() && ok;
		ok = checkDataForIdEnding(transaction) && ok;

		return ok;
	}

	protected boolean checkDataForIdRegistryEntry() {
		return checkDataForIdRegistryEntry(null);
	}

	protected boolean checkDataForIdRegistryEntry(final DBTransaction transaction) {
		if (isIdRegistryEntryEmpty()) {
			if (isIdRegistryEntryRequired()) {
				monthlyOnWeekdayInternals.addErrorMessage(id, "idRegistryEntry", getIdRegistryEntryLabel(), getIdRegistryEntryEmptyErrorMessage());
				return false;
			}
		} else if (!isIdRegistryEntryOK(transaction)) {
			monthlyOnWeekdayInternals.addErrorMessage(id, "idRegistryEntry", getIdRegistryEntryLabel(), getIdRegistryEntryBadFormatErrorMessage());
			return false;
		} else if (isIdRegistryEntryToBeUnique() && !isIdRegistryEntryUnique()) {
			monthlyOnWeekdayInternals.addErrorMessage(id, "idRegistryEntry", getIdRegistryEntryLabel(), getIdRegistryEntryNotUniqueErrorMessage());
			return false;
		}

		return true;
	}

	protected boolean checkDataForIdWeekdayPlaceInMonth() {
		return checkDataForIdWeekdayPlaceInMonth(null);
	}

	protected boolean checkDataForIdWeekdayPlaceInMonth(final DBTransaction transaction) {
		if (isIdWeekdayPlaceInMonthEmpty()) {
			if (isIdWeekdayPlaceInMonthRequired()) {
				monthlyOnWeekdayInternals.addErrorMessage(id, "idWeekdayPlaceInMonth", getIdWeekdayPlaceInMonthLabel(), getIdWeekdayPlaceInMonthEmptyErrorMessage());
				return false;
			}
		} else if (!isIdWeekdayPlaceInMonthOK(transaction)) {
			monthlyOnWeekdayInternals.addErrorMessage(id, "idWeekdayPlaceInMonth", getIdWeekdayPlaceInMonthLabel(), getIdWeekdayPlaceInMonthBadFormatErrorMessage());
			return false;
		} else if (isIdWeekdayPlaceInMonthToBeUnique() && !isIdWeekdayPlaceInMonthUnique()) {
			monthlyOnWeekdayInternals.addErrorMessage(id, "idWeekdayPlaceInMonth", getIdWeekdayPlaceInMonthLabel(), getIdWeekdayPlaceInMonthNotUniqueErrorMessage());
			return false;
		}

		return true;
	}

	protected boolean checkDataForIdWeekday() {
		return checkDataForIdWeekday(null);
	}

	protected boolean checkDataForIdWeekday(final DBTransaction transaction) {
		if (isIdWeekdayEmpty()) {
			if (isIdWeekdayRequired()) {
				monthlyOnWeekdayInternals.addErrorMessage(id, "idWeekday", getIdWeekdayLabel(), getIdWeekdayEmptyErrorMessage());
				return false;
			}
		} else if (!isIdWeekdayOK(transaction)) {
			monthlyOnWeekdayInternals.addErrorMessage(id, "idWeekday", getIdWeekdayLabel(), getIdWeekdayBadFormatErrorMessage());
			return false;
		} else if (isIdWeekdayToBeUnique() && !isIdWeekdayUnique()) {
			monthlyOnWeekdayInternals.addErrorMessage(id, "idWeekday", getIdWeekdayLabel(), getIdWeekdayNotUniqueErrorMessage());
			return false;
		}

		return true;
	}

	protected boolean checkDataForEveryXMonth() {
		if (isEveryXMonthEmpty()) {
			if (isEveryXMonthRequired()) {
				monthlyOnWeekdayInternals.addErrorMessage(id, "everyXMonth", getEveryXMonthLabel(), getEveryXMonthEmptyErrorMessage());
				return false;
			}
		} else if (!isEveryXMonthOK()) {
			monthlyOnWeekdayInternals.addErrorMessage(id, "everyXMonth", getEveryXMonthLabel(), getEveryXMonthBadFormatErrorMessage());
			return false;
		} else if (isEveryXMonthToBeUnique() && !isEveryXMonthUnique()) {
			monthlyOnWeekdayInternals.addErrorMessage(id, "everyXMonth", getEveryXMonthLabel(), getEveryXMonthNotUniqueErrorMessage());
			return false;
		}

		return true;
	}

	protected boolean checkDataForStart() {
		if (isStartEmpty()) {
			if (isStartRequired()) {
				monthlyOnWeekdayInternals.addErrorMessage(id, "start", getStartLabel(), getStartEmptyErrorMessage());
				return false;
			}
		} else if (!isStartOK()) {
			monthlyOnWeekdayInternals.addErrorMessage(id, "start", getStartLabel(), getStartBadFormatErrorMessage());
			return false;
		} else if (isStartToBeUnique() && !isStartUnique()) {
			monthlyOnWeekdayInternals.addErrorMessage(id, "start", getStartLabel(), getStartNotUniqueErrorMessage());
			return false;
		}

		return true;
	}

	protected boolean checkDataForIdEnding() {
		return checkDataForIdEnding(null);
	}

	protected boolean checkDataForIdEnding(final DBTransaction transaction) {
		if (isIdEndingEmpty()) {
			if (isIdEndingRequired()) {
				monthlyOnWeekdayInternals.addErrorMessage(id, "idEnding", getIdEndingLabel(), getIdEndingEmptyErrorMessage());
				return false;
			}
		} else if (!isIdEndingOK(transaction)) {
			monthlyOnWeekdayInternals.addErrorMessage(id, "idEnding", getIdEndingLabel(), getIdEndingBadFormatErrorMessage());
			return false;
		} else if (isIdEndingToBeUnique() && !isIdEndingUnique()) {
			monthlyOnWeekdayInternals.addErrorMessage(id, "idEnding", getIdEndingLabel(), getIdEndingNotUniqueErrorMessage());
			return false;
		}

		return true;
	}

	public boolean isIdRegistryEntryEmpty() {
		return idRegistryEntry == 0;
	}

	public boolean isIdWeekdayPlaceInMonthEmpty() {
		return idWeekdayPlaceInMonth == 0;
	}

	public boolean isIdWeekdayEmpty() {
		return idWeekday == 0;
	}

	public boolean isEveryXMonthEmpty() {
		return Strings.isEmpty(everyXMonthStr);
	}

	public boolean isStartEmpty() {
		return Strings.isEmpty(startStr);
	}

	public boolean isIdEndingEmpty() {
		return idEnding == 0;
	}

	public String getIdRegistryEntryEmptyErrorMessage() {
		return monthlyOnWeekdayInternals.getRequiredErrorMessage("idRegistryEntry");
	}

	public String getIdWeekdayPlaceInMonthEmptyErrorMessage() {
		return monthlyOnWeekdayInternals.getRequiredErrorMessage("idWeekdayPlaceInMonth");
	}

	public String getIdWeekdayEmptyErrorMessage() {
		return monthlyOnWeekdayInternals.getRequiredErrorMessage("idWeekday");
	}

	public String getEveryXMonthEmptyErrorMessage() {
		return monthlyOnWeekdayInternals.getRequiredErrorMessage("everyXMonth");
	}

	public String getStartEmptyErrorMessage() {
		return monthlyOnWeekdayInternals.getRequiredErrorMessage("start");
	}

	public String getIdEndingEmptyErrorMessage() {
		return monthlyOnWeekdayInternals.getRequiredErrorMessage("idEnding");
	}

	public boolean isIdRegistryEntryOK() {
		return isIdRegistryEntryOK(null);
	}

	protected boolean isIdRegistryEntryOK(final DBTransaction transaction) {
		if (transaction == null)
			return RegistryEntry.isIdOK(idRegistryEntry);

		return RegistryEntry.isIdOK(idRegistryEntry, transaction);
	}

	public boolean isIdWeekdayPlaceInMonthOK() {
		return isIdWeekdayPlaceInMonthOK(null);
	}

	protected boolean isIdWeekdayPlaceInMonthOK(final DBTransaction transaction) {
		if (transaction == null)
			return WeekdayPlaceInMonth.isIdOK(idWeekdayPlaceInMonth);

		return WeekdayPlaceInMonth.isIdOK(idWeekdayPlaceInMonth, transaction);
	}

	public boolean isIdWeekdayOK() {
		return isIdWeekdayOK(null);
	}

	protected boolean isIdWeekdayOK(final DBTransaction transaction) {
		if (transaction == null)
			return Weekday.isIdOK(idWeekday);

		return Weekday.isIdOK(idWeekday, transaction);
	}

	public boolean isEveryXMonthOK() {
		return FormatCheckHelper.isIntNumber(everyXMonthStr);
	}

	public boolean isStartOK() {
		return validateDateFormat(startStr);
	}

	public boolean isIdEndingOK() {
		return isIdEndingOK(null);
	}

	protected boolean isIdEndingOK(final DBTransaction transaction) {
		if (transaction == null)
			return Ending.isIdOK(idEnding);

		return Ending.isIdOK(idEnding, transaction);
	}

	public String getIdRegistryEntryBadFormatErrorMessage() {
		return monthlyOnWeekdayInternals.getBadFormatErrorMessage("idRegistryEntry");
	}

	public String getIdWeekdayPlaceInMonthBadFormatErrorMessage() {
		return monthlyOnWeekdayInternals.getBadFormatErrorMessage("idWeekdayPlaceInMonth");
	}

	public String getIdWeekdayBadFormatErrorMessage() {
		return monthlyOnWeekdayInternals.getBadFormatErrorMessage("idWeekday");
	}

	public String getEveryXMonthBadFormatErrorMessage() {
		return monthlyOnWeekdayInternals.getBadFormatErrorMessage("everyXMonth");
	}

	public String getStartBadFormatErrorMessage() {
		return monthlyOnWeekdayInternals.getBadFormatErrorMessage("start");
	}

	public String getIdEndingBadFormatErrorMessage() {
		return monthlyOnWeekdayInternals.getBadFormatErrorMessage("idEnding");
	}

	public boolean isIdRegistryEntryUnique() {
		return !dbAccess.processQuery("SELECT id FROM schdlr_monthly_on_weekday WHERE id_registry_entry=? AND id <> ?", new BooleanCheckQuery() {
			@Override
			public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
				stat.setLong(1, idRegistryEntry);
				stat.setLong(2, id);
			}
		});
	}

	public boolean isIdWeekdayPlaceInMonthUnique() {
		return !dbAccess.processQuery("SELECT id FROM schdlr_monthly_on_weekday WHERE id_weekday_place_in_month=? AND id <> ?", new BooleanCheckQuery() {
			@Override
			public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
				stat.setLong(1, idWeekdayPlaceInMonth);
				stat.setLong(2, id);
			}
		});
	}

	public boolean isIdWeekdayUnique() {
		return !dbAccess.processQuery("SELECT id FROM schdlr_monthly_on_weekday WHERE id_weekday=? AND id <> ?", new BooleanCheckQuery() {
			@Override
			public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
				stat.setLong(1, idWeekday);
				stat.setLong(2, id);
			}
		});
	}

	public boolean isEveryXMonthUnique() {
		return !dbAccess.processQuery("SELECT id FROM schdlr_monthly_on_weekday WHERE every_x_month=? AND id <> ?", new BooleanCheckQuery() {
			@Override
			public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
				stat.setInt(1, everyXMonth);
				stat.setLong(2, id);
			}
		});
	}

	public boolean isStartUnique() {
		return !dbAccess.processQuery("SELECT id FROM schdlr_monthly_on_weekday WHERE start=? AND id <> ?", new BooleanCheckQuery() {
			@Override
			public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
				stat.setDate(1, start);
				stat.setLong(2, id);
			}
		});
	}

	public boolean isIdEndingUnique() {
		return !dbAccess.processQuery("SELECT id FROM schdlr_monthly_on_weekday WHERE id_ending=? AND id <> ?", new BooleanCheckQuery() {
			@Override
			public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
				stat.setLong(1, idEnding);
				stat.setLong(2, id);
			}
		});
	}

	public String getIdRegistryEntryNotUniqueErrorMessage() {
		return monthlyOnWeekdayInternals.getNotUniqueErrorMessage("idRegistryEntry");
	}

	public String getIdWeekdayPlaceInMonthNotUniqueErrorMessage() {
		return monthlyOnWeekdayInternals.getNotUniqueErrorMessage("idWeekdayPlaceInMonth");
	}

	public String getIdWeekdayNotUniqueErrorMessage() {
		return monthlyOnWeekdayInternals.getNotUniqueErrorMessage("idWeekday");
	}

	public String getEveryXMonthNotUniqueErrorMessage() {
		return monthlyOnWeekdayInternals.getNotUniqueErrorMessage("everyXMonth");
	}

	public String getStartNotUniqueErrorMessage() {
		return monthlyOnWeekdayInternals.getNotUniqueErrorMessage("start");
	}

	public String getIdEndingNotUniqueErrorMessage() {
		return monthlyOnWeekdayInternals.getNotUniqueErrorMessage("idEnding");
	}

	@Override
	public List<ErrorMessage> getErrorMessages() {
		return monthlyOnWeekdayInternals.getErrorMessages();
	}

	@Override
	public void reset() {
		idRegistryEntry = 0;
		idWeekdayPlaceInMonth = 0;
		idWeekday = 0;
		everyXMonth = 0;
		everyXMonthStr = "";
		start = null;
		startStr = "";
		idEnding = 0;
		monthlyOnWeekdayInternals.clearErrorMessages();
	}

	@Override
	public void fullReset() {
		reset();
		id = 0;
	}

	@Override
	public void delete() {
		final DBTransaction transaction = createDBTransaction();
		delete(transaction);
		transaction.commit();

		postDeleteActions();

		if (MONTHLY_ON_WEEKDAY_PARAMETERS.USE_CACHE)
			MONTHLY_ON_WEEKDAY_PARAMETERS.CACHE_SET.delete(id);

		fullReset();
	}

	public void delete(final DBTransaction transaction) {
		preDeleteExtraDbActions(transaction);
		transaction.addUpdate("DELETE FROM schdlr_monthly_on_weekday WHERE id=?", new DBQuerySetup() {
				@Override
				public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
					stat.setLong(1, id);
				}
			});
		deleteExtraDbActions(transaction);
	}

	protected void preDeleteExtraDbActions(final DBTransaction transaction) { }

	protected void deleteExtraDbActions(final DBTransaction transaction) { }

	protected void postDeleteActions() { }

	private class RecordCreationSetup implements DBQuerySetup {
		@Override
		public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
			stat.setLong(1, idRegistryEntry);
			stat.setLong(2, idWeekdayPlaceInMonth);
			stat.setLong(3, idWeekday);
			stat.setInt(4, everyXMonth);
			stat.setDate(5, start);
			if (idEnding == 0)
				stat.setNull(6, java.sql.Types.INTEGER);
			else
				stat.setLong(6, idEnding);
		}
	}

	private class RecordUpdateSetup extends RecordCreationSetup {
		@Override
		public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
			super.setupPreparedStatement(stat);
			stat.setLong(7, id);
		}
	}

	private void createRecord() {
		final DBTransaction transaction = createDBTransaction();
		id = createRecord(transaction);
		transaction.commit();
		postCreateActions();
		updateCaching();
	}

	private long createRecord(final DBTransaction transaction) {
		preCreateExtraDbActions(transaction);
		final long id = transaction.addRecordCreation("INSERT INTO schdlr_monthly_on_weekday (id_registry_entry, id_weekday_place_in_month, id_weekday, every_x_month, start, id_ending) VALUES (?, ?, ?, ?, ?, ?)", new RecordCreationSetup());
		createExtraDbActions(transaction, id);
		return id;
	}

	protected void preCreateExtraDbActions(final DBTransaction transaction) { }

	protected void createExtraDbActions(final DBTransaction transaction, final long id) { }

	protected void postCreateActions() { }

	private void updateRecord() {
		final DBTransaction transaction = createDBTransaction();
		updateRecord(transaction);
		transaction.commit();
		postUpdateActions();
		updateCaching();
	}

	private void updateRecord(final DBTransaction transaction) {
		preUpdateExtraDbActions(transaction);
		transaction.addUpdate("UPDATE schdlr_monthly_on_weekday SET id_registry_entry=?, id_weekday_place_in_month=?, id_weekday=?, every_x_month=?, start=?, id_ending=? WHERE id=?", new RecordUpdateSetup());
		updateExtraDbActions(transaction);
	}

	protected void preUpdateExtraDbActions(final DBTransaction transaction) { }

	protected void updateExtraDbActions(final DBTransaction transaction) { }

	protected void postUpdateActions() { }

	private void updateCaching() {
		if (MONTHLY_ON_WEEKDAY_PARAMETERS.USE_CACHE)
			MONTHLY_ON_WEEKDAY_PARAMETERS.CACHE_SET.submit((MonthlyOnWeekday) this);
	}

	protected String formatDate(final Date date) {
		return DateFormat.getDateInstance(DateFormat.LONG, monthlyOnWeekdayInternals.getLocale()).format(date);
	}

	protected Date convertStringToDate(final String str) {
		return Dates.getDateFromYYMD(str, "-");
	}

	protected String convertDateToString(final Date date) {
		if (date == null)
			return "";

		return date.toString();
	}

	protected boolean validateDateFormat(final String str) {
		final SimpleInputDateFormat simpleInputDateFormat = new SimpleInputDateFormat(SimpleInputDateFormat.ElementOrder.YYMD, "-");
		return simpleInputDateFormat.validate(str);
	}

	public static List<MonthlyOnWeekday> getAll() {
		return getAll(MONTHLY_ON_WEEKDAY_PARAMETERS.getOrderByFields());
	}

	protected static List<MonthlyOnWeekday> getAll(final String orderBy) {
		return getSelection(null, orderBy, null);
	}

	private static class GetSelectionQueryProcess implements DBQueryRetrieveData<List<MonthlyOnWeekday>> {
		@Override
		public List<MonthlyOnWeekday> processResultSet(final ResultSet rs) throws SQLException {
			final List<MonthlyOnWeekday> list = new ArrayList<MonthlyOnWeekday>();

			while (rs.next())
				list.add(new MonthlyOnWeekday(rs.getLong(1), rs.getLong(2), rs.getLong(3), rs.getLong(4), rs.getInt(5), rs.getDate(6), rs.getLong(7)));


			return list;
		}
	}

	protected static List<MonthlyOnWeekday> getSelection(final String whereClause) {
		return getSelection(whereClause, null);
	}

	protected static List<MonthlyOnWeekday> getSelection(final String whereClause, final DBQuerySetup setup) {
		return getSelection(whereClause, MONTHLY_ON_WEEKDAY_PARAMETERS.getOrderByFields(), setup);
	}

	protected static List<MonthlyOnWeekday> getSelection(final String whereClause, final String orderBy, final DBQuerySetup setup) {
		if (whereClause == null && setup != null)
			throw new IllegalArgumentException("Cannot accept setup code without a WHERE clause.");

		final StringBuilder query = new StringBuilder();
		query.append("SELECT id, id_registry_entry, id_weekday_place_in_month, id_weekday, every_x_month, start, id_ending FROM schdlr_monthly_on_weekday");
		if (whereClause != null)
			query.append(" WHERE ").append(whereClause);
		if (orderBy != null)
			query.append(" ORDER BY ").append(orderBy);

		if (whereClause == null || setup == null)
			return dbAccess.processQuery(query.toString(), new GetSelectionQueryProcess());

		return dbAccess.processQuery(query.toString(), setup, new GetSelectionQueryProcess());
	}

	private static class GetSelectionCountQueryProcess implements DBQueryRetrieveData<Long> {
		@Override
		public Long processResultSet(final ResultSet rs) throws SQLException {
			rs.next();
			return rs.getLong(1);
		}
	}

	protected static long getSelectionCount(final String whereClause) {
		return getSelectionCount(whereClause, null);
	}

	protected static long getSelectionCount(final String whereClause, final DBQuerySetup setup) {
		final String query = "SELECT COUNT(id) FROM schdlr_monthly_on_weekday WHERE " + whereClause;

		if (setup == null)
			return dbAccess.processQuery(query, new GetSelectionCountQueryProcess());

		return dbAccess.processQuery(query, setup, new GetSelectionCountQueryProcess());
	}

	public static List<IdNamePair> getIdNamePairs(final List<String> dataFields, final List<String> orderingFields) {
		return getIdNamePairs(null, dataFields, orderingFields);
	}

	protected static List<IdNamePair> getIdNamePairs(final String whereClause, final List<String> dataFields, final List<String> orderingFields) {
		return DBQueries.getIdNamePairs(db, "schdlr_monthly_on_weekday", whereClause, dataFields, orderingFields);
	}

	public static long getCount() {
		return DBQueries.getLongCount(db, "schdlr_monthly_on_weekday");
	}

	public static boolean isIdOK(final long id) {
		return DBQueries.isIdOK(db, "schdlr_monthly_on_weekday", id);
	}

	public static boolean isIdOK(final long id, final DBTransaction transaction) {
		return DBQueries.isIdOK(transaction, "schdlr_monthly_on_weekday", id);
	}

	public static String getHumanReadableTitle(final long id) {
		if (id == 0)
			return "";

		return DBQueries.getHumanReadableTitle(db, "schdlr_monthly_on_weekday", id, MONTHLY_ON_WEEKDAY_PARAMETERS.getNamingFields());
	}

	public static List<MonthlyOnWeekday> getList(final ResultSet rs) throws SQLException {
		final List<MonthlyOnWeekday> list = new ArrayList<MonthlyOnWeekday>();

		while (rs.next())
			list.add(new MonthlyOnWeekday(rs));


		return list;
	}

	@Override
	public void setLocale(final Locale locale) {
		monthlyOnWeekdayInternals.setLocale(locale);
	}

}

