// Generated by BeanMaker, on April 1, 2018 4:06:01 AM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import org.beanmaker.util.DbBeanCacheSet;

public class MonthlyOnWeekdayParameters extends MonthlyOnWeekdayParametersBase {
	public static final DbBeanCacheSet<MonthlyOnWeekday> CACHE_SET = null;
	public static final boolean USE_CACHE = CACHE_SET != null;
}

