// Generated by BeanMaker, on April 1, 2018 4:18:32 AM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import org.beanmaker.util.DbBeanCacheSet;

public class OnSpecificDateParameters extends OnSpecificDateParametersBase {
	public static final DbBeanCacheSet<OnSpecificDate> CACHE_SET = null;
	public static final boolean USE_CACHE = CACHE_SET != null;
}

