// Generated by BeanMaker, on March 31, 2018 2:21:12 AM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import org.beanmaker.util.DbBeanCacheSet;

public class RegistryEntryTypeParameters extends RegistryEntryTypeParametersBase {
	public static final DbBeanCacheSet<RegistryEntryType> CACHE_SET = null;
	public static final boolean USE_CACHE = CACHE_SET != null;
}

