// Generated by BeanMaker, on April 1, 2018 1:53:46 AM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import org.beanmaker.util.BeanInternals;
import org.beanmaker.util.DBQueries;
import org.beanmaker.util.DbBeanInterface;
import org.beanmaker.util.ErrorMessage;
import org.beanmaker.util.IdNamePair;
import org.beanmaker.util.ToStringMaker;

import org.dbbeans.sql.DBQueryRetrieveData;
import org.dbbeans.sql.DBQuerySetup;
import org.dbbeans.sql.DBQuerySetupProcess;
import org.dbbeans.sql.DBTransaction;

import org.dbbeans.sql.queries.BooleanCheckQuery;

import org.dbbeans.util.Strings;

public abstract class RegistryEntryTypeBase extends DbBean implements DbBeanInterface {
	private long id;
	private String code = "";
	private String javaClass = "";

	protected static final String DATABASE_TABLE_NAME = "schdlr_registry_entry_types";
	protected static final String DATABASE_FIELD_LIST = "schdlr_registry_entry_types.id, schdlr_registry_entry_types.code, schdlr_registry_entry_types.java_class";

	protected final BeanInternals registryEntryTypeInternals = new BeanInternals("org-dbbeans-scheduler-RegistryEntryType");
	protected static final RegistryEntryTypeParameters REGISTRY_ENTRY_TYPE_PARAMETERS = new RegistryEntryTypeParameters();

	public RegistryEntryTypeBase() { }

	public RegistryEntryTypeBase(final long id) {
		setId(id);
	}

	public RegistryEntryTypeBase(final RegistryEntryTypeBase registryEntryTypeModel) {
		id = 0;
		code = registryEntryTypeModel.code;
		javaClass = registryEntryTypeModel.javaClass;
	}

	protected RegistryEntryTypeBase(final long id, final String code, final String javaClass) {
		this.id = id;
		this.code = code;
		this.javaClass = javaClass;
	}

	protected RegistryEntryTypeBase(final ResultSet rs) throws SQLException {
		this(rs.getLong(1), rs.getString(2), rs.getString(3));
	}

	@Override
	public void setId(final long id) {
		class DataFromDBQuery implements DBQuerySetupProcess {
			String code = null;
			String javaClass = null;
			boolean idOK = false;

			@Override
			public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
				stat.setLong(1, id);
			}

			@Override
			public void processResultSet(final ResultSet rs) throws SQLException {
				if (rs.next()) {
					code = rs.getString(1);
					javaClass = rs.getString(2);
					idOK = true;
				}
			}
		}

		if (id <= 0)
			throw new IllegalArgumentException("id = " + id + " <= 0");

		final DataFromDBQuery dataFromDBQuery = new DataFromDBQuery();
		dbAccess.processQuery("SELECT code, java_class FROM schdlr_registry_entry_types WHERE id=?", dataFromDBQuery);

		if (!dataFromDBQuery.idOK)
			throw new IllegalArgumentException("id = " + id + " does not exist");

		initExtraDbActions(id);

		this.id = id;
		this.code = dataFromDBQuery.code;
		this.javaClass = dataFromDBQuery.javaClass;

		postInitActions();
	}

	protected void initExtraDbActions(final long id) { }

	protected void postInitActions() { }

	@Override
	public void resetId() {
		id = 0;
	}

	public void refreshFromDataBase() {
		if (id == 0)
			throw new IllegalArgumentException("Cannot refresh bean not yet commited to database");

		setId(id);
	}

	@Override
	public boolean equals(final Object object) {
		if (id == 0)
			return false;

		if (object instanceof RegistryEntryType)
			return ((RegistryEntryType) object).getId() == id;

		return false;
	}

	@Override
	public int hashCode() {
		if (id == 0)
			return -1;

		return 31 * ((int) (id ^ (id >>> 32))) + 17;
	}

	@Override
	public String toString() {
		final ToStringMaker stringMaker = new ToStringMaker(this);
		stringMaker.addField("code", code);
		stringMaker.addField("javaClass", javaClass);
		return stringMaker.toString();
	}

	public void setCode(final String code) {
		this.code = code;
	}

	public void setJavaClass(final String javaClass) {
		this.javaClass = javaClass;
	}

	@Override
	public long getId() {
		return id;
	}

	public String getCode() {
		return code;
	}

	public String getJavaClass() {
		return javaClass;
	}

	public String getCodeLabel() {
		return registryEntryTypeInternals.getLabel("code");
	}

	public String getJavaClassLabel() {
		return registryEntryTypeInternals.getLabel("javaClass");
	}

	public boolean isIdRequired() {
		return true;
	}

	public boolean isCodeRequired() {
		return true;
	}

	public boolean isJavaClassRequired() {
		return true;
	}

	public boolean isIdToBeUnique() {
		return true;
	}

	public boolean isCodeToBeUnique() {
		return true;
	}

	public boolean isJavaClassToBeUnique() {
		return false;
	}

	@Override
	public void updateDB() {
		preUpdateConversions();

		if (id == 0) {
			createRecord();
			return;
		}

		if (id > 0) {
			updateRecord();
			return;
		}

		assert (false) : "id < 0 ?!?";
	}

	public long updateDB(final DBTransaction transaction) {
		if (REGISTRY_ENTRY_TYPE_PARAMETERS.USE_CACHE)
			throw new UnsupportedOperationException("Cannot cache intermediate updates.");

		preUpdateConversions(transaction);

		if (id == 0) {
			id = createRecord(transaction);
			return id;
		}

		if (id > 0) {
			updateRecord(transaction);
			return id;
		}

		assert (false) : "id < 0 ?!?";
		return -1;
	}

	@Override
	public void preUpdateConversions() {
		preUpdateConversions(null);
	}

	protected void preUpdateConversions(final DBTransaction transaction) {
		if (!isDataOK(transaction))
			throw new IllegalArgumentException(ErrorMessage.toStrings(getErrorMessages()));

	}

	@Override
	public boolean isDataOK() {
		return isDataOK(null);
	}

	protected boolean isDataOK(final DBTransaction transaction) {
		registryEntryTypeInternals.clearErrorMessages();
		boolean ok = true;

		ok = checkDataForCode() && ok;
		ok = checkDataForJavaClass() && ok;

		return ok;
	}

	protected boolean checkDataForCode() {
		if (isCodeEmpty()) {
			if (isCodeRequired()) {
				registryEntryTypeInternals.addErrorMessage(id, "code", getCodeLabel(), getCodeEmptyErrorMessage());
				return false;
			}
		} else if (!isCodeOK()) {
			registryEntryTypeInternals.addErrorMessage(id, "code", getCodeLabel(), getCodeBadFormatErrorMessage());
			return false;
		} else if (isCodeToBeUnique() && !isCodeUnique()) {
			registryEntryTypeInternals.addErrorMessage(id, "code", getCodeLabel(), getCodeNotUniqueErrorMessage());
			return false;
		}

		return true;
	}

	protected boolean checkDataForJavaClass() {
		if (isJavaClassEmpty()) {
			if (isJavaClassRequired()) {
				registryEntryTypeInternals.addErrorMessage(id, "javaClass", getJavaClassLabel(), getJavaClassEmptyErrorMessage());
				return false;
			}
		} else if (!isJavaClassOK()) {
			registryEntryTypeInternals.addErrorMessage(id, "javaClass", getJavaClassLabel(), getJavaClassBadFormatErrorMessage());
			return false;
		} else if (isJavaClassToBeUnique() && !isJavaClassUnique()) {
			registryEntryTypeInternals.addErrorMessage(id, "javaClass", getJavaClassLabel(), getJavaClassNotUniqueErrorMessage());
			return false;
		}

		return true;
	}

	public boolean isCodeEmpty() {
		return Strings.isEmpty(code);
	}

	public boolean isJavaClassEmpty() {
		return Strings.isEmpty(javaClass);
	}

	public String getCodeEmptyErrorMessage() {
		return registryEntryTypeInternals.getRequiredErrorMessage("code");
	}

	public String getJavaClassEmptyErrorMessage() {
		return registryEntryTypeInternals.getRequiredErrorMessage("javaClass");
	}

	public boolean isCodeOK() {
		return true;
	}

	public boolean isJavaClassOK() {
		return true;
	}

	public String getCodeBadFormatErrorMessage() {
		return registryEntryTypeInternals.getBadFormatErrorMessage("code");
	}

	public String getJavaClassBadFormatErrorMessage() {
		return registryEntryTypeInternals.getBadFormatErrorMessage("javaClass");
	}

	public boolean isCodeUnique() {
		return !dbAccess.processQuery("SELECT id FROM schdlr_registry_entry_types WHERE code=? AND id <> ?", new BooleanCheckQuery() {
			@Override
			public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
				stat.setString(1, code);
				stat.setLong(2, id);
			}
		});
	}

	public boolean isJavaClassUnique() {
		return !dbAccess.processQuery("SELECT id FROM schdlr_registry_entry_types WHERE java_class=? AND id <> ?", new BooleanCheckQuery() {
			@Override
			public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
				stat.setString(1, javaClass);
				stat.setLong(2, id);
			}
		});
	}

	public String getCodeNotUniqueErrorMessage() {
		return registryEntryTypeInternals.getNotUniqueErrorMessage("code");
	}

	public String getJavaClassNotUniqueErrorMessage() {
		return registryEntryTypeInternals.getNotUniqueErrorMessage("javaClass");
	}

	@Override
	public List<ErrorMessage> getErrorMessages() {
		return registryEntryTypeInternals.getErrorMessages();
	}

	@Override
	public void reset() {
		code = "";
		javaClass = "";
		registryEntryTypeInternals.clearErrorMessages();
	}

	@Override
	public void fullReset() {
		reset();
		id = 0;
	}

	@Override
	public void delete() {
		final DBTransaction transaction = createDBTransaction();
		delete(transaction);
		transaction.commit();

		postDeleteActions();

		if (REGISTRY_ENTRY_TYPE_PARAMETERS.USE_CACHE)
			REGISTRY_ENTRY_TYPE_PARAMETERS.CACHE_SET.delete(id);

		fullReset();
	}

	public void delete(final DBTransaction transaction) {
		preDeleteExtraDbActions(transaction);
		transaction.addUpdate("DELETE FROM schdlr_registry_entry_types WHERE id=?", new DBQuerySetup() {
				@Override
				public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
					stat.setLong(1, id);
				}
			});
		deleteExtraDbActions(transaction);
	}

	protected void preDeleteExtraDbActions(final DBTransaction transaction) { }

	protected void deleteExtraDbActions(final DBTransaction transaction) { }

	protected void postDeleteActions() { }

	private class RecordCreationSetup implements DBQuerySetup {
		@Override
		public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
			stat.setString(1, code);
			stat.setString(2, javaClass);
		}
	}

	private class RecordUpdateSetup extends RecordCreationSetup {
		@Override
		public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
			super.setupPreparedStatement(stat);
			stat.setLong(3, id);
		}
	}

	private void createRecord() {
		final DBTransaction transaction = createDBTransaction();
		id = createRecord(transaction);
		transaction.commit();
		postCreateActions();
		updateCaching();
	}

	private long createRecord(final DBTransaction transaction) {
		preCreateExtraDbActions(transaction);
		final long id = transaction.addRecordCreation("INSERT INTO schdlr_registry_entry_types (code, java_class) VALUES (?, ?)", new RecordCreationSetup());
		createExtraDbActions(transaction, id);
		return id;
	}

	protected void preCreateExtraDbActions(final DBTransaction transaction) { }

	protected void createExtraDbActions(final DBTransaction transaction, final long id) { }

	protected void postCreateActions() { }

	private void updateRecord() {
		final DBTransaction transaction = createDBTransaction();
		updateRecord(transaction);
		transaction.commit();
		postUpdateActions();
		updateCaching();
	}

	private void updateRecord(final DBTransaction transaction) {
		preUpdateExtraDbActions(transaction);
		transaction.addUpdate("UPDATE schdlr_registry_entry_types SET code=?, java_class=? WHERE id=?", new RecordUpdateSetup());
		updateExtraDbActions(transaction);
	}

	protected void preUpdateExtraDbActions(final DBTransaction transaction) { }

	protected void updateExtraDbActions(final DBTransaction transaction) { }

	protected void postUpdateActions() { }

	private void updateCaching() {
		if (REGISTRY_ENTRY_TYPE_PARAMETERS.USE_CACHE)
			REGISTRY_ENTRY_TYPE_PARAMETERS.CACHE_SET.submit((RegistryEntryType) this);
	}

	public static List<RegistryEntryType> getAll() {
		return getAll(REGISTRY_ENTRY_TYPE_PARAMETERS.getOrderByFields());
	}

	protected static List<RegistryEntryType> getAll(final String orderBy) {
		return getSelection(null, orderBy, null);
	}

	private static class GetSelectionQueryProcess implements DBQueryRetrieveData<List<RegistryEntryType>> {
		@Override
		public List<RegistryEntryType> processResultSet(final ResultSet rs) throws SQLException {
			final List<RegistryEntryType> list = new ArrayList<RegistryEntryType>();

			while (rs.next())
				list.add(new RegistryEntryType(rs.getLong(1), rs.getString(2), rs.getString(3)));


			return list;
		}
	}

	protected static List<RegistryEntryType> getSelection(final String whereClause) {
		return getSelection(whereClause, null);
	}

	protected static List<RegistryEntryType> getSelection(final String whereClause, final DBQuerySetup setup) {
		return getSelection(whereClause, REGISTRY_ENTRY_TYPE_PARAMETERS.getOrderByFields(), setup);
	}

	protected static List<RegistryEntryType> getSelection(final String whereClause, final String orderBy, final DBQuerySetup setup) {
		if (whereClause == null && setup != null)
			throw new IllegalArgumentException("Cannot accept setup code without a WHERE clause.");

		final StringBuilder query = new StringBuilder();
		query.append("SELECT id, code, java_class FROM schdlr_registry_entry_types");
		if (whereClause != null)
			query.append(" WHERE ").append(whereClause);
		if (orderBy != null)
			query.append(" ORDER BY ").append(orderBy);

		if (whereClause == null || setup == null)
			return dbAccess.processQuery(query.toString(), new GetSelectionQueryProcess());

		return dbAccess.processQuery(query.toString(), setup, new GetSelectionQueryProcess());
	}

	private static class GetSelectionCountQueryProcess implements DBQueryRetrieveData<Long> {
		@Override
		public Long processResultSet(final ResultSet rs) throws SQLException {
			rs.next();
			return rs.getLong(1);
		}
	}

	protected static long getSelectionCount(final String whereClause) {
		return getSelectionCount(whereClause, null);
	}

	protected static long getSelectionCount(final String whereClause, final DBQuerySetup setup) {
		final String query = "SELECT COUNT(id) FROM schdlr_registry_entry_types WHERE " + whereClause;

		if (setup == null)
			return dbAccess.processQuery(query, new GetSelectionCountQueryProcess());

		return dbAccess.processQuery(query, setup, new GetSelectionCountQueryProcess());
	}

	public static List<IdNamePair> getIdNamePairs(final List<String> dataFields, final List<String> orderingFields) {
		return getIdNamePairs(null, dataFields, orderingFields);
	}

	protected static List<IdNamePair> getIdNamePairs(final String whereClause, final List<String> dataFields, final List<String> orderingFields) {
		return DBQueries.getIdNamePairs(db, "schdlr_registry_entry_types", whereClause, dataFields, orderingFields);
	}

	public static long getCount() {
		return DBQueries.getLongCount(db, "schdlr_registry_entry_types");
	}

	public static boolean isIdOK(final long id) {
		return DBQueries.isIdOK(db, "schdlr_registry_entry_types", id);
	}

	public static boolean isIdOK(final long id, final DBTransaction transaction) {
		return DBQueries.isIdOK(transaction, "schdlr_registry_entry_types", id);
	}

	public static String getHumanReadableTitle(final long id) {
		if (id == 0)
			return "";

		return DBQueries.getHumanReadableTitle(db, "schdlr_registry_entry_types", id, REGISTRY_ENTRY_TYPE_PARAMETERS.getNamingFields());
	}

	public static List<RegistryEntryType> getList(final ResultSet rs) throws SQLException {
		final List<RegistryEntryType> list = new ArrayList<RegistryEntryType>();

		while (rs.next())
			list.add(new RegistryEntryType(rs));


		return list;
	}

	@Override
	public void setLocale(final Locale locale) {
		registryEntryTypeInternals.setLocale(locale);
	}

}

