// Generated by BeanMaker, on March 31, 2018 2:45:41 AM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import java.sql.ResultSet;
import java.sql.SQLException;

public class RegistryEntry extends RegistryEntryBase {
	public RegistryEntry() { }

	public RegistryEntry(final long id) {
		super(id);
	}

	public RegistryEntry(final RegistryEntry registryEntryModel) {
		super(registryEntryModel);
	}

	protected RegistryEntry(final long id, final String code, final long idType, final boolean active) {
		super(id, code, idType, active);
	}

	protected RegistryEntry(final ResultSet rs) throws SQLException {
		super(rs);
	}

}

