// Generated by BeanMaker, on March 31, 2018 2:45:41 AM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import org.beanmaker.util.DbBeanCacheSet;

public class RegistryEntryParameters extends RegistryEntryParametersBase {
	public static final DbBeanCacheSet<RegistryEntry> CACHE_SET = null;
	public static final boolean USE_CACHE = CACHE_SET != null;
}

