// Generated by BeanMaker, on April 1, 2018 4:35:29 AM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import org.dbbeans.sql.DBTransaction;

import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;

public class Weekly extends WeeklyBase {
	public Weekly() { }

	public Weekly(final long id) {
		super(id);
	}

	public Weekly(final Weekly weeklyModel) {
		super(weeklyModel);
	}

	protected Weekly(final long id, final long idRegistryEntry, final int everyXWeek, final Date start, final long idEnding) {
		super(id, idRegistryEntry, everyXWeek, start, idEnding);
	}

	protected Weekly(final ResultSet rs) throws SQLException {
		super(rs);
	}

	public boolean hasEnding() {
		return !isIdEndingEmpty();
	}

	@Override
	protected void preDeleteExtraDbActions(DBTransaction transaction) {
		if (hasEnding())
			getEnding().delete(transaction);
	}
}

