// Generated by BeanMaker, on April 1, 2018 4:35:29 AM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import org.beanmaker.util.DbBeanCacheSet;

public class WeeklyParameters extends WeeklyParametersBase {
	public static final DbBeanCacheSet<Weekly> CACHE_SET = null;
	public static final boolean USE_CACHE = CACHE_SET != null;
}

