// Generated by BeanMaker, on April 1, 2018 3:44:26 AM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import java.sql.ResultSet;
import java.sql.SQLException;

public class Weekday extends WeekdayBase {
	public Weekday() { }

	public Weekday(final long id) {
		super(id);
	}

	public Weekday(final Weekday weekdayModel) {
		super(weekdayModel);
	}

	protected Weekday(final long id, final String code) {
		super(id, code);
	}

	protected Weekday(final ResultSet rs) throws SQLException {
		super(rs);
	}

}

