// Generated by BeanMaker, on April 1, 2018 3:33:39 AM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import java.sql.ResultSet;
import java.sql.SQLException;

public class WeekdayPlaceInMonth extends WeekdayPlaceInMonthBase {
	public WeekdayPlaceInMonth() { }

	public WeekdayPlaceInMonth(final long id) {
		super(id);
	}

	public WeekdayPlaceInMonth(final WeekdayPlaceInMonth weekdayPlaceInMonthModel) {
		super(weekdayPlaceInMonthModel);
	}

	protected WeekdayPlaceInMonth(final long id, final String code) {
		super(id, code);
	}

	protected WeekdayPlaceInMonth(final ResultSet rs) throws SQLException {
		super(rs);
	}

}

