// Generated by BeanMaker, on April 1, 2018 3:33:39 AM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import org.beanmaker.util.DbBeanCacheSet;

public class WeekdayPlaceInMonthParameters extends WeekdayPlaceInMonthParametersBase {
	public static final DbBeanCacheSet<WeekdayPlaceInMonth> CACHE_SET = null;
	public static final boolean USE_CACHE = CACHE_SET != null;
}

