// Generated by BeanMaker, on April 1, 2018 5:01:20 PM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import org.dbbeans.sql.DBTransaction;

import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;

public class YearlyOnDay extends YearlyOnDayBase {
	public YearlyOnDay() { }

	public YearlyOnDay(final long id) {
		super(id);
	}

	public YearlyOnDay(final YearlyOnDay yearlyOnDayModel) {
		super(yearlyOnDayModel);
	}

	protected YearlyOnDay(final long id, final long idRegistryEntry, final int everyXYear, final Date onDay, final Date start, final long idEnding) {
		super(id, idRegistryEntry, everyXYear, onDay, start, idEnding);
	}

	protected YearlyOnDay(final ResultSet rs) throws SQLException {
		super(rs);
	}

	public boolean hasEnding() {
		return !isIdEndingEmpty();
	}

	@Override
	protected void preDeleteExtraDbActions(DBTransaction transaction) {
		if (hasEnding())
			getEnding().delete(transaction);
	}
}

