// Generated by BeanMaker, on April 1, 2018 5:01:20 PM CEST
// Library Version #0.9.12-beta

package org.dbbeans.scheduler;

import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.text.DateFormat;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import org.beanmaker.util.BeanInternals;
import org.beanmaker.util.DBQueries;
import org.beanmaker.util.DbBeanInterface;
import org.beanmaker.util.ErrorMessage;
import org.beanmaker.util.FormatCheckHelper;
import org.beanmaker.util.IdNamePair;
import org.beanmaker.util.ToStringMaker;

import org.dbbeans.sql.DBQueryRetrieveData;
import org.dbbeans.sql.DBQuerySetup;
import org.dbbeans.sql.DBQuerySetupProcess;
import org.dbbeans.sql.DBTransaction;

import org.dbbeans.sql.queries.BooleanCheckQuery;

import org.dbbeans.util.Dates;
import org.dbbeans.util.SimpleInputDateFormat;
import org.dbbeans.util.Strings;

public abstract class YearlyOnDayBase extends DbBean implements DbBeanInterface {
	private long id;
	private long idRegistryEntry;
	private int everyXYear;
	private String everyXYearStr = "";
	private Date onDay;
	private String onDayStr = "";
	private Date start;
	private String startStr = "";
	private long idEnding;

	protected static final String DATABASE_TABLE_NAME = "schdlr_yearly_on_day";
	protected static final String DATABASE_FIELD_LIST = "schdlr_yearly_on_day.id, schdlr_yearly_on_day.id_registry_entry, schdlr_yearly_on_day.every_x_year, schdlr_yearly_on_day.on_day, schdlr_yearly_on_day.start, schdlr_yearly_on_day.id_ending";

	protected final BeanInternals yearlyOnDayInternals = new BeanInternals("org-dbbeans-scheduler-YearlyOnDay");
	protected static final YearlyOnDayParameters YEARLY_ON_DAY_PARAMETERS = new YearlyOnDayParameters();

	public YearlyOnDayBase() { }

	public YearlyOnDayBase(final long id) {
		setId(id);
	}

	public YearlyOnDayBase(final YearlyOnDayBase yearlyOnDayModel) {
		id = 0;
		idRegistryEntry = yearlyOnDayModel.idRegistryEntry;
		setEveryXYear(yearlyOnDayModel.everyXYear);
		setOnDay(yearlyOnDayModel.onDay);
		setStart(yearlyOnDayModel.start);
		idEnding = yearlyOnDayModel.idEnding;
	}

	protected YearlyOnDayBase(final long id, final long idRegistryEntry, final int everyXYear, final Date onDay, final Date start, final long idEnding) {
		this.id = id;
		this.idRegistryEntry = idRegistryEntry;
		setEveryXYear(everyXYear);
		setOnDay(onDay);
		setStart(start);
		this.idEnding = idEnding;
	}

	protected YearlyOnDayBase(final ResultSet rs) throws SQLException {
		this(rs.getLong(1), rs.getLong(2), rs.getInt(3), rs.getDate(4), rs.getDate(5), rs.getLong(6));
	}

	@Override
	public void setId(final long id) {
		class DataFromDBQuery implements DBQuerySetupProcess {
			long idRegistryEntry = 0;
			int everyXYear = 0;
			Date onDay = null;
			Date start = null;
			long idEnding = 0;
			boolean idOK = false;

			@Override
			public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
				stat.setLong(1, id);
			}

			@Override
			public void processResultSet(final ResultSet rs) throws SQLException {
				if (rs.next()) {
					idRegistryEntry = rs.getLong(1);
					everyXYear = rs.getInt(2);
					onDay = rs.getDate(3);
					start = rs.getDate(4);
					idEnding = rs.getLong(5);
					idOK = true;
				}
			}
		}

		if (id <= 0)
			throw new IllegalArgumentException("id = " + id + " <= 0");

		final DataFromDBQuery dataFromDBQuery = new DataFromDBQuery();
		dbAccess.processQuery("SELECT id_registry_entry, every_x_year, on_day, start, id_ending FROM schdlr_yearly_on_day WHERE id=?", dataFromDBQuery);

		if (!dataFromDBQuery.idOK)
			throw new IllegalArgumentException("id = " + id + " does not exist");

		initExtraDbActions(id);

		this.id = id;
		this.idRegistryEntry = dataFromDBQuery.idRegistryEntry;
		this.everyXYear = dataFromDBQuery.everyXYear;
		everyXYearStr = String.valueOf(everyXYear);
		this.onDay = dataFromDBQuery.onDay;
		onDayStr = convertDateToString(onDay);
		this.start = dataFromDBQuery.start;
		startStr = convertDateToString(start);
		this.idEnding = dataFromDBQuery.idEnding;

		postInitActions();
	}

	protected void initExtraDbActions(final long id) { }

	protected void postInitActions() { }

	@Override
	public void resetId() {
		id = 0;
	}

	public void refreshFromDataBase() {
		if (id == 0)
			throw new IllegalArgumentException("Cannot refresh bean not yet commited to database");

		setId(id);
	}

	@Override
	public boolean equals(final Object object) {
		if (id == 0)
			return false;

		if (object instanceof YearlyOnDay)
			return ((YearlyOnDay) object).getId() == id;

		return false;
	}

	@Override
	public int hashCode() {
		if (id == 0)
			return -1;

		return 31 * ((int) (id ^ (id >>> 32))) + 17;
	}

	@Override
	public String toString() {
		final ToStringMaker stringMaker = new ToStringMaker(this);
		stringMaker.addField("idRegistryEntry", idRegistryEntry);
		stringMaker.addField("everyXYear", everyXYear);
		stringMaker.addField("everyXYearStr", everyXYearStr);
		stringMaker.addField("onDay", onDay);
		stringMaker.addField("onDayStr", onDayStr);
		stringMaker.addField("start", start);
		stringMaker.addField("startStr", startStr);
		stringMaker.addField("idEnding", idEnding);
		return stringMaker.toString();
	}

	public void setIdRegistryEntry(final long idRegistryEntry) {
		this.idRegistryEntry = idRegistryEntry;
	}

	public void setRegistryEntry(final RegistryEntry registryEntry) {
		if (registryEntry.getId() == 0)
			throw new IllegalArgumentException("Cannot accept uninitialized RegistryEntry bean (id = 0) as argument.");

		idRegistryEntry = registryEntry.getId();
	}

	public void setEveryXYear(final int everyXYear) {
		this.everyXYear = everyXYear;
		everyXYearStr = Integer.toString(everyXYear);
	}

	public void setEveryXYearStr(final String everyXYearStr) {
		this.everyXYearStr = everyXYearStr;
	}

	public void setOnDay(final Date onDay) {
		if (onDay == null)
			this.onDay = null;
		else
			this.onDay = new Date(onDay.getTime());
		onDayStr = convertDateToString(onDay);
	}

	public void setOnDayStr(final String onDayStr) {
		this.onDayStr = onDayStr;
	}

	public void setStart(final Date start) {
		if (start == null)
			this.start = null;
		else
			this.start = new Date(start.getTime());
		startStr = convertDateToString(start);
	}

	public void setStartStr(final String startStr) {
		this.startStr = startStr;
	}

	public void setIdEnding(final long idEnding) {
		this.idEnding = idEnding;
	}

	public void setEnding(final Ending ending) {
		if (ending.getId() == 0)
			throw new IllegalArgumentException("Cannot accept uninitialized Ending bean (id = 0) as argument.");

		idEnding = ending.getId();
	}

	@Override
	public long getId() {
		return id;
	}

	public long getIdRegistryEntry() {
		return idRegistryEntry;
	}

	public RegistryEntry getRegistryEntry() {
		return new RegistryEntry(idRegistryEntry);
	}

	public int getEveryXYear() {
		return everyXYear;
	}

	public String getEveryXYearStr() {
		return everyXYearStr;
	}

	public Date getOnDay() {
		if (onDay == null)
			return null;

		return new Date(onDay.getTime());
	}

	public String getOnDayStr() {
		return onDayStr;
	}

	public String getOnDayFormatted() {
		if (isOnDayEmpty()) {
			if (isOnDayRequired())
				throw new IllegalArgumentException("Cannot display bad data");
			return "";
		}

		if (!isOnDayOK())
			throw new IllegalArgumentException("Cannot display bad data");

		return formatDate(convertStringToDate(onDayStr));
	}

	public Date getStart() {
		if (start == null)
			return null;

		return new Date(start.getTime());
	}

	public String getStartStr() {
		return startStr;
	}

	public String getStartFormatted() {
		if (isStartEmpty()) {
			if (isStartRequired())
				throw new IllegalArgumentException("Cannot display bad data");
			return "";
		}

		if (!isStartOK())
			throw new IllegalArgumentException("Cannot display bad data");

		return formatDate(convertStringToDate(startStr));
	}

	public long getIdEnding() {
		return idEnding;
	}

	public Ending getEnding() {
		return new Ending(idEnding);
	}

	public String getIdRegistryEntryLabel() {
		return yearlyOnDayInternals.getLabel("idRegistryEntry");
	}

	public String getEveryXYearLabel() {
		return yearlyOnDayInternals.getLabel("everyXYear");
	}

	public String getOnDayLabel() {
		return yearlyOnDayInternals.getLabel("onDay");
	}

	public String getStartLabel() {
		return yearlyOnDayInternals.getLabel("start");
	}

	public String getIdEndingLabel() {
		return yearlyOnDayInternals.getLabel("idEnding");
	}

	public boolean isIdRequired() {
		return true;
	}

	public boolean isIdRegistryEntryRequired() {
		return true;
	}

	public boolean isEveryXYearRequired() {
		return true;
	}

	public boolean isOnDayRequired() {
		return true;
	}

	public boolean isStartRequired() {
		return true;
	}

	public boolean isIdEndingRequired() {
		return false;
	}

	public boolean isIdToBeUnique() {
		return true;
	}

	public boolean isIdRegistryEntryToBeUnique() {
		return true;
	}

	public boolean isEveryXYearToBeUnique() {
		return false;
	}

	public boolean isOnDayToBeUnique() {
		return false;
	}

	public boolean isStartToBeUnique() {
		return false;
	}

	public boolean isIdEndingToBeUnique() {
		return true;
	}

	@Override
	public void updateDB() {
		preUpdateConversions();

		if (id == 0) {
			createRecord();
			return;
		}

		if (id > 0) {
			updateRecord();
			return;
		}

		assert (false) : "id < 0 ?!?";
	}

	public long updateDB(final DBTransaction transaction) {
		if (YEARLY_ON_DAY_PARAMETERS.USE_CACHE)
			throw new UnsupportedOperationException("Cannot cache intermediate updates.");

		preUpdateConversions(transaction);

		if (id == 0) {
			id = createRecord(transaction);
			return id;
		}

		if (id > 0) {
			updateRecord(transaction);
			return id;
		}

		assert (false) : "id < 0 ?!?";
		return -1;
	}

	@Override
	public void preUpdateConversions() {
		preUpdateConversions(null);
	}

	protected void preUpdateConversions(final DBTransaction transaction) {
		if (!isDataOK(transaction))
			throw new IllegalArgumentException(ErrorMessage.toStrings(getErrorMessages()));

		everyXYear = Strings.getIntVal(everyXYearStr);
		if (!Strings.isEmpty(onDayStr))
			onDay = convertStringToDate(onDayStr);
		else
			onDay = null;
		if (!Strings.isEmpty(startStr))
			start = convertStringToDate(startStr);
		else
			start = null;
	}

	@Override
	public boolean isDataOK() {
		return isDataOK(null);
	}

	protected boolean isDataOK(final DBTransaction transaction) {
		yearlyOnDayInternals.clearErrorMessages();
		boolean ok = true;

		ok = checkDataForIdRegistryEntry(transaction) && ok;
		ok = checkDataForEveryXYear() && ok;
		ok = checkDataForOnDay() && ok;
		ok = checkDataForStart() && ok;
		ok = checkDataForIdEnding(transaction) && ok;

		return ok;
	}

	protected boolean checkDataForIdRegistryEntry() {
		return checkDataForIdRegistryEntry(null);
	}

	protected boolean checkDataForIdRegistryEntry(final DBTransaction transaction) {
		if (isIdRegistryEntryEmpty()) {
			if (isIdRegistryEntryRequired()) {
				yearlyOnDayInternals.addErrorMessage(id, "idRegistryEntry", getIdRegistryEntryLabel(), getIdRegistryEntryEmptyErrorMessage());
				return false;
			}
		} else if (!isIdRegistryEntryOK(transaction)) {
			yearlyOnDayInternals.addErrorMessage(id, "idRegistryEntry", getIdRegistryEntryLabel(), getIdRegistryEntryBadFormatErrorMessage());
			return false;
		} else if (isIdRegistryEntryToBeUnique() && !isIdRegistryEntryUnique()) {
			yearlyOnDayInternals.addErrorMessage(id, "idRegistryEntry", getIdRegistryEntryLabel(), getIdRegistryEntryNotUniqueErrorMessage());
			return false;
		}

		return true;
	}

	protected boolean checkDataForEveryXYear() {
		if (isEveryXYearEmpty()) {
			if (isEveryXYearRequired()) {
				yearlyOnDayInternals.addErrorMessage(id, "everyXYear", getEveryXYearLabel(), getEveryXYearEmptyErrorMessage());
				return false;
			}
		} else if (!isEveryXYearOK()) {
			yearlyOnDayInternals.addErrorMessage(id, "everyXYear", getEveryXYearLabel(), getEveryXYearBadFormatErrorMessage());
			return false;
		} else if (isEveryXYearToBeUnique() && !isEveryXYearUnique()) {
			yearlyOnDayInternals.addErrorMessage(id, "everyXYear", getEveryXYearLabel(), getEveryXYearNotUniqueErrorMessage());
			return false;
		}

		return true;
	}

	protected boolean checkDataForOnDay() {
		if (isOnDayEmpty()) {
			if (isOnDayRequired()) {
				yearlyOnDayInternals.addErrorMessage(id, "onDay", getOnDayLabel(), getOnDayEmptyErrorMessage());
				return false;
			}
		} else if (!isOnDayOK()) {
			yearlyOnDayInternals.addErrorMessage(id, "onDay", getOnDayLabel(), getOnDayBadFormatErrorMessage());
			return false;
		} else if (isOnDayToBeUnique() && !isOnDayUnique()) {
			yearlyOnDayInternals.addErrorMessage(id, "onDay", getOnDayLabel(), getOnDayNotUniqueErrorMessage());
			return false;
		}

		return true;
	}

	protected boolean checkDataForStart() {
		if (isStartEmpty()) {
			if (isStartRequired()) {
				yearlyOnDayInternals.addErrorMessage(id, "start", getStartLabel(), getStartEmptyErrorMessage());
				return false;
			}
		} else if (!isStartOK()) {
			yearlyOnDayInternals.addErrorMessage(id, "start", getStartLabel(), getStartBadFormatErrorMessage());
			return false;
		} else if (isStartToBeUnique() && !isStartUnique()) {
			yearlyOnDayInternals.addErrorMessage(id, "start", getStartLabel(), getStartNotUniqueErrorMessage());
			return false;
		}

		return true;
	}

	protected boolean checkDataForIdEnding() {
		return checkDataForIdEnding(null);
	}

	protected boolean checkDataForIdEnding(final DBTransaction transaction) {
		if (isIdEndingEmpty()) {
			if (isIdEndingRequired()) {
				yearlyOnDayInternals.addErrorMessage(id, "idEnding", getIdEndingLabel(), getIdEndingEmptyErrorMessage());
				return false;
			}
		} else if (!isIdEndingOK(transaction)) {
			yearlyOnDayInternals.addErrorMessage(id, "idEnding", getIdEndingLabel(), getIdEndingBadFormatErrorMessage());
			return false;
		} else if (isIdEndingToBeUnique() && !isIdEndingUnique()) {
			yearlyOnDayInternals.addErrorMessage(id, "idEnding", getIdEndingLabel(), getIdEndingNotUniqueErrorMessage());
			return false;
		}

		return true;
	}

	public boolean isIdRegistryEntryEmpty() {
		return idRegistryEntry == 0;
	}

	public boolean isEveryXYearEmpty() {
		return Strings.isEmpty(everyXYearStr);
	}

	public boolean isOnDayEmpty() {
		return Strings.isEmpty(onDayStr);
	}

	public boolean isStartEmpty() {
		return Strings.isEmpty(startStr);
	}

	public boolean isIdEndingEmpty() {
		return idEnding == 0;
	}

	public String getIdRegistryEntryEmptyErrorMessage() {
		return yearlyOnDayInternals.getRequiredErrorMessage("idRegistryEntry");
	}

	public String getEveryXYearEmptyErrorMessage() {
		return yearlyOnDayInternals.getRequiredErrorMessage("everyXYear");
	}

	public String getOnDayEmptyErrorMessage() {
		return yearlyOnDayInternals.getRequiredErrorMessage("onDay");
	}

	public String getStartEmptyErrorMessage() {
		return yearlyOnDayInternals.getRequiredErrorMessage("start");
	}

	public String getIdEndingEmptyErrorMessage() {
		return yearlyOnDayInternals.getRequiredErrorMessage("idEnding");
	}

	public boolean isIdRegistryEntryOK() {
		return isIdRegistryEntryOK(null);
	}

	protected boolean isIdRegistryEntryOK(final DBTransaction transaction) {
		if (transaction == null)
			return RegistryEntry.isIdOK(idRegistryEntry);

		return RegistryEntry.isIdOK(idRegistryEntry, transaction);
	}

	public boolean isEveryXYearOK() {
		return FormatCheckHelper.isIntNumber(everyXYearStr);
	}

	public boolean isOnDayOK() {
		return validateDateFormat(onDayStr);
	}

	public boolean isStartOK() {
		return validateDateFormat(startStr);
	}

	public boolean isIdEndingOK() {
		return isIdEndingOK(null);
	}

	protected boolean isIdEndingOK(final DBTransaction transaction) {
		if (transaction == null)
			return Ending.isIdOK(idEnding);

		return Ending.isIdOK(idEnding, transaction);
	}

	public String getIdRegistryEntryBadFormatErrorMessage() {
		return yearlyOnDayInternals.getBadFormatErrorMessage("idRegistryEntry");
	}

	public String getEveryXYearBadFormatErrorMessage() {
		return yearlyOnDayInternals.getBadFormatErrorMessage("everyXYear");
	}

	public String getOnDayBadFormatErrorMessage() {
		return yearlyOnDayInternals.getBadFormatErrorMessage("onDay");
	}

	public String getStartBadFormatErrorMessage() {
		return yearlyOnDayInternals.getBadFormatErrorMessage("start");
	}

	public String getIdEndingBadFormatErrorMessage() {
		return yearlyOnDayInternals.getBadFormatErrorMessage("idEnding");
	}

	public boolean isIdRegistryEntryUnique() {
		return !dbAccess.processQuery("SELECT id FROM schdlr_yearly_on_day WHERE id_registry_entry=? AND id <> ?", new BooleanCheckQuery() {
			@Override
			public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
				stat.setLong(1, idRegistryEntry);
				stat.setLong(2, id);
			}
		});
	}

	public boolean isEveryXYearUnique() {
		return !dbAccess.processQuery("SELECT id FROM schdlr_yearly_on_day WHERE every_x_year=? AND id <> ?", new BooleanCheckQuery() {
			@Override
			public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
				stat.setInt(1, everyXYear);
				stat.setLong(2, id);
			}
		});
	}

	public boolean isOnDayUnique() {
		return !dbAccess.processQuery("SELECT id FROM schdlr_yearly_on_day WHERE on_day=? AND id <> ?", new BooleanCheckQuery() {
			@Override
			public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
				stat.setDate(1, onDay);
				stat.setLong(2, id);
			}
		});
	}

	public boolean isStartUnique() {
		return !dbAccess.processQuery("SELECT id FROM schdlr_yearly_on_day WHERE start=? AND id <> ?", new BooleanCheckQuery() {
			@Override
			public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
				stat.setDate(1, start);
				stat.setLong(2, id);
			}
		});
	}

	public boolean isIdEndingUnique() {
		return !dbAccess.processQuery("SELECT id FROM schdlr_yearly_on_day WHERE id_ending=? AND id <> ?", new BooleanCheckQuery() {
			@Override
			public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
				stat.setLong(1, idEnding);
				stat.setLong(2, id);
			}
		});
	}

	public String getIdRegistryEntryNotUniqueErrorMessage() {
		return yearlyOnDayInternals.getNotUniqueErrorMessage("idRegistryEntry");
	}

	public String getEveryXYearNotUniqueErrorMessage() {
		return yearlyOnDayInternals.getNotUniqueErrorMessage("everyXYear");
	}

	public String getOnDayNotUniqueErrorMessage() {
		return yearlyOnDayInternals.getNotUniqueErrorMessage("onDay");
	}

	public String getStartNotUniqueErrorMessage() {
		return yearlyOnDayInternals.getNotUniqueErrorMessage("start");
	}

	public String getIdEndingNotUniqueErrorMessage() {
		return yearlyOnDayInternals.getNotUniqueErrorMessage("idEnding");
	}

	@Override
	public List<ErrorMessage> getErrorMessages() {
		return yearlyOnDayInternals.getErrorMessages();
	}

	@Override
	public void reset() {
		idRegistryEntry = 0;
		everyXYear = 0;
		everyXYearStr = "";
		onDay = null;
		onDayStr = "";
		start = null;
		startStr = "";
		idEnding = 0;
		yearlyOnDayInternals.clearErrorMessages();
	}

	@Override
	public void fullReset() {
		reset();
		id = 0;
	}

	@Override
	public void delete() {
		final DBTransaction transaction = createDBTransaction();
		delete(transaction);
		transaction.commit();

		postDeleteActions();

		if (YEARLY_ON_DAY_PARAMETERS.USE_CACHE)
			YEARLY_ON_DAY_PARAMETERS.CACHE_SET.delete(id);

		fullReset();
	}

	public void delete(final DBTransaction transaction) {
		preDeleteExtraDbActions(transaction);
		transaction.addUpdate("DELETE FROM schdlr_yearly_on_day WHERE id=?", new DBQuerySetup() {
				@Override
				public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
					stat.setLong(1, id);
				}
			});
		deleteExtraDbActions(transaction);
	}

	protected void preDeleteExtraDbActions(final DBTransaction transaction) { }

	protected void deleteExtraDbActions(final DBTransaction transaction) { }

	protected void postDeleteActions() { }

	private class RecordCreationSetup implements DBQuerySetup {
		@Override
		public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
			stat.setLong(1, idRegistryEntry);
			stat.setInt(2, everyXYear);
			stat.setDate(3, onDay);
			stat.setDate(4, start);
			if (idEnding == 0)
				stat.setNull(5, java.sql.Types.INTEGER);
			else
				stat.setLong(5, idEnding);
		}
	}

	private class RecordUpdateSetup extends RecordCreationSetup {
		@Override
		public void setupPreparedStatement(final PreparedStatement stat) throws SQLException {
			super.setupPreparedStatement(stat);
			stat.setLong(6, id);
		}
	}

	private void createRecord() {
		final DBTransaction transaction = createDBTransaction();
		id = createRecord(transaction);
		transaction.commit();
		postCreateActions();
		updateCaching();
	}

	private long createRecord(final DBTransaction transaction) {
		preCreateExtraDbActions(transaction);
		final long id = transaction.addRecordCreation("INSERT INTO schdlr_yearly_on_day (id_registry_entry, every_x_year, on_day, start, id_ending) VALUES (?, ?, ?, ?, ?)", new RecordCreationSetup());
		createExtraDbActions(transaction, id);
		return id;
	}

	protected void preCreateExtraDbActions(final DBTransaction transaction) { }

	protected void createExtraDbActions(final DBTransaction transaction, final long id) { }

	protected void postCreateActions() { }

	private void updateRecord() {
		final DBTransaction transaction = createDBTransaction();
		updateRecord(transaction);
		transaction.commit();
		postUpdateActions();
		updateCaching();
	}

	private void updateRecord(final DBTransaction transaction) {
		preUpdateExtraDbActions(transaction);
		transaction.addUpdate("UPDATE schdlr_yearly_on_day SET id_registry_entry=?, every_x_year=?, on_day=?, start=?, id_ending=? WHERE id=?", new RecordUpdateSetup());
		updateExtraDbActions(transaction);
	}

	protected void preUpdateExtraDbActions(final DBTransaction transaction) { }

	protected void updateExtraDbActions(final DBTransaction transaction) { }

	protected void postUpdateActions() { }

	private void updateCaching() {
		if (YEARLY_ON_DAY_PARAMETERS.USE_CACHE)
			YEARLY_ON_DAY_PARAMETERS.CACHE_SET.submit((YearlyOnDay) this);
	}

	protected String formatDate(final Date date) {
		return DateFormat.getDateInstance(DateFormat.LONG, yearlyOnDayInternals.getLocale()).format(date);
	}

	protected Date convertStringToDate(final String str) {
		return Dates.getDateFromYYMD(str, "-");
	}

	protected String convertDateToString(final Date date) {
		if (date == null)
			return "";

		return date.toString();
	}

	protected boolean validateDateFormat(final String str) {
		final SimpleInputDateFormat simpleInputDateFormat = new SimpleInputDateFormat(SimpleInputDateFormat.ElementOrder.YYMD, "-");
		return simpleInputDateFormat.validate(str);
	}

	public static List<YearlyOnDay> getAll() {
		return getAll(YEARLY_ON_DAY_PARAMETERS.getOrderByFields());
	}

	protected static List<YearlyOnDay> getAll(final String orderBy) {
		return getSelection(null, orderBy, null);
	}

	private static class GetSelectionQueryProcess implements DBQueryRetrieveData<List<YearlyOnDay>> {
		@Override
		public List<YearlyOnDay> processResultSet(final ResultSet rs) throws SQLException {
			final List<YearlyOnDay> list = new ArrayList<YearlyOnDay>();

			while (rs.next())
				list.add(new YearlyOnDay(rs.getLong(1), rs.getLong(2), rs.getInt(3), rs.getDate(4), rs.getDate(5), rs.getLong(6)));


			return list;
		}
	}

	protected static List<YearlyOnDay> getSelection(final String whereClause) {
		return getSelection(whereClause, null);
	}

	protected static List<YearlyOnDay> getSelection(final String whereClause, final DBQuerySetup setup) {
		return getSelection(whereClause, YEARLY_ON_DAY_PARAMETERS.getOrderByFields(), setup);
	}

	protected static List<YearlyOnDay> getSelection(final String whereClause, final String orderBy, final DBQuerySetup setup) {
		if (whereClause == null && setup != null)
			throw new IllegalArgumentException("Cannot accept setup code without a WHERE clause.");

		final StringBuilder query = new StringBuilder();
		query.append("SELECT id, id_registry_entry, every_x_year, on_day, start, id_ending FROM schdlr_yearly_on_day");
		if (whereClause != null)
			query.append(" WHERE ").append(whereClause);
		if (orderBy != null)
			query.append(" ORDER BY ").append(orderBy);

		if (whereClause == null || setup == null)
			return dbAccess.processQuery(query.toString(), new GetSelectionQueryProcess());

		return dbAccess.processQuery(query.toString(), setup, new GetSelectionQueryProcess());
	}

	private static class GetSelectionCountQueryProcess implements DBQueryRetrieveData<Long> {
		@Override
		public Long processResultSet(final ResultSet rs) throws SQLException {
			rs.next();
			return rs.getLong(1);
		}
	}

	protected static long getSelectionCount(final String whereClause) {
		return getSelectionCount(whereClause, null);
	}

	protected static long getSelectionCount(final String whereClause, final DBQuerySetup setup) {
		final String query = "SELECT COUNT(id) FROM schdlr_yearly_on_day WHERE " + whereClause;

		if (setup == null)
			return dbAccess.processQuery(query, new GetSelectionCountQueryProcess());

		return dbAccess.processQuery(query, setup, new GetSelectionCountQueryProcess());
	}

	public static List<IdNamePair> getIdNamePairs(final List<String> dataFields, final List<String> orderingFields) {
		return getIdNamePairs(null, dataFields, orderingFields);
	}

	protected static List<IdNamePair> getIdNamePairs(final String whereClause, final List<String> dataFields, final List<String> orderingFields) {
		return DBQueries.getIdNamePairs(db, "schdlr_yearly_on_day", whereClause, dataFields, orderingFields);
	}

	public static long getCount() {
		return DBQueries.getLongCount(db, "schdlr_yearly_on_day");
	}

	public static boolean isIdOK(final long id) {
		return DBQueries.isIdOK(db, "schdlr_yearly_on_day", id);
	}

	public static boolean isIdOK(final long id, final DBTransaction transaction) {
		return DBQueries.isIdOK(transaction, "schdlr_yearly_on_day", id);
	}

	public static String getHumanReadableTitle(final long id) {
		if (id == 0)
			return "";

		return DBQueries.getHumanReadableTitle(db, "schdlr_yearly_on_day", id, YEARLY_ON_DAY_PARAMETERS.getNamingFields());
	}

	public static List<YearlyOnDay> getList(final ResultSet rs) throws SQLException {
		final List<YearlyOnDay> list = new ArrayList<YearlyOnDay>();

		while (rs.next())
			list.add(new YearlyOnDay(rs));


		return list;
	}

	@Override
	public void setLocale(final Locale locale) {
		yearlyOnDayInternals.setLocale(locale);
	}

}

